/**
 * Content model + static reference data for the Cheatsheets & Documentation
 * Hub (spec Module 5). No React imports here — this file is data only,
 * rendered by a future `src/adapters/ui/tools/CheatsheetsScreen.tsx`.
 *
 * Everything below is static/const on purpose: the app is client-first and
 * offline, so cheatsheet content ships in the bundle instead of being
 * fetched over the network.
 */

/**
 * A single reference row: a command/pattern/key on the left, what it does,
 * and a short worked example of using it.
 */
export interface CheatsheetEntry {
  /**
   * The command, regex token, sysctl key, cron field/shortcut, or octal
   * digit being documented. Rendered in a monospace font by the UI.
   */
  command: string
  /** Plain-language explanation of what it does. */
  description: string
  /** Short worked example (an invocation, a matched string, a config line). */
  example: string
}

/** A titled group of related `entries` within a `CheatsheetPage`. */
export interface CheatsheetSection {
  title: string
  entries: CheatsheetEntry[]
}

/** One full cheatsheet, e.g. "Git Commands" or "Chmod Permissions". */
export interface CheatsheetPage {
  /**
   * Stable slug for the currently-selected-page UI state — independent of
   * `title` so a copy edit never breaks the "which page was open" state.
   */
  id: string
  title: string
  /** One-line summary shown under the page title. */
  description: string
  sections: CheatsheetSection[]
}

/**
 * What kind of thing an external resource actually is. This matters because
 * "official docs for a project" (documentation), "a GitHub repo that is
 * itself just a curated list of other links" (curatedList), "a hands-on
 * practice/exercise repo" (exercise), and "a structured learning path"
 * (roadmap) serve very different purposes even though they're all just a
 * name + URL on the surface.
 *
 * The `ai*` / `mcpServer` / `automation` / `catalog` / `devService` values
 * back the Knowledge Hub's "AI & Automation" group (see
 * KNOWLEDGE_HUB_AI_EXPANSION_PLAN.md):
 * - catalog     — a directory/aggregator of many tools (AI tool indexes, model rankings)
 * - mcpServer   — MCP servers, gateways, registries
 * - aiFramework — agent / AI-dev frameworks & SDKs
 * - aiApp       — end-user AI software / agents / products
 * - aiSkill     — agent-skill ecosystems, SKILL.md, skill marketplaces
 * - automation  — automation platforms & workflow engines
 * - aiModel     — a foundation model plus its official tooling / harness
 * - devService  — hosted infra products: tunnels, static hosts, PaaS, deploy platforms
 */
export type ResourceType =
  | 'documentation'
  | 'curatedList'
  | 'exercise'
  | 'roadmap'
  | 'catalog'
  | 'mcpServer'
  | 'aiFramework'
  | 'aiApp'
  | 'aiSkill'
  | 'automation'
  | 'aiModel'
  | 'devService'

/**
 * Display order for `groupByType` rendering. Only lists types that currently
 * have at least one entry in `EXTERNAL_RESOURCE_LINKS` — new AI/automation
 * types are appended here as their seed content lands (plan phases D1–D5), so
 * the "every listed type has content" test stays honest.
 */
export const RESOURCE_TYPES: ResourceType[] = ['documentation', 'curatedList', 'exercise', 'roadmap']

/**
 * A curated external resource link (spec 5.2: External Resources). The UI
 * renders these as selectable text, not tappable links.
 */
export interface ReferenceLink {
  name: string
  url: string
  description: string
  /**
   * The primary kind this link is — drives which Knowledge Hub screen shows
   * it. See `ResourceType`.
   */
  type: ResourceType
  /**
   * Free-form topic tags (e.g. 'devops', 'system-design') used to build the
   * filter chips and to match against the search box in the UI.
   */
  tags: string[]
  /**
   * True when the link is itself an index / directory / aggregator rather
   * than a single project (an "awesome-*" repo, an MCP registry, a "there's
   * an AI for that" site). The `/tools/ai-catalogs` screen collects every
   * `isDirectory` entry across types; individual screens may surface their
   * own directories in a separate band. Absent = a single tool/project.
   */
  isDirectory?: boolean
}

// ---------------------------------------------------------------------------
// Cheatsheet pages
//
// Ported 1:1 from the Dart reference implementation
// (lib/core/cheatsheets/cheatsheet_content.dart). The sysctl page's
// "Network (net.core.* / net.ipv4.*)" section entries are cross-checked
// against the keys generated by the (not yet ported) Linux sysctl tuner
// tool rather than invented independently.
// ---------------------------------------------------------------------------

const gitPage: CheatsheetPage = {
  id: 'git',
  title: 'Git Commands',
  description: 'The commands people actually reach for, day to day.',
  sections: [
    {
      title: 'Setup & Cloning',
      entries: [
        {
          command: 'git init',
          description: 'Initialize a new, empty Git repository in the current directory.',
          example: 'git init\ngit init my-project',
        },
        {
          command: 'git clone',
          description: 'Clone an existing repository into a new directory, copying its full history.',
          example: 'git clone https://github.com/user/repo.git',
        },
      ],
    },
    {
      title: 'Staging & Committing',
      entries: [
        {
          command: 'git status',
          description: 'Show the working tree status: staged, unstaged, and untracked changes.',
          example: 'git status',
        },
        {
          command: 'git add',
          description: 'Stage file changes so they are included in the next commit.',
          example: 'git add file.txt\ngit add -A',
        },
        {
          command: 'git commit',
          description: 'Record the currently staged changes as a new commit in the history.',
          example: 'git commit -m "Fix login bug"',
        },
      ],
    },
    {
      title: 'Branching & Merging',
      entries: [
        {
          command: 'git branch',
          description: 'List local branches, or create/delete one.',
          example: 'git branch feature-x\ngit branch -d feature-x',
        },
        {
          command: 'git checkout',
          description: 'Switch branches or restore working-tree files. Legacy multi-purpose command.',
          example: 'git checkout main\ngit checkout -- file.txt',
        },
        {
          command: 'git switch',
          description: 'Switch the current branch (Git 2.23+). Replaces checkout for branch switching.',
          example: 'git switch main\ngit switch -c new-feature',
        },
        {
          command: 'git merge',
          description: 'Join two or more development histories together into the current branch.',
          example: 'git merge feature-x',
        },
        {
          command: 'git rebase',
          description: 'Reapply commits from the current branch on top of another base commit.',
          example: 'git rebase main\ngit rebase -i HEAD~3',
        },
      ],
    },
    {
      title: 'Inspecting History',
      entries: [
        {
          command: 'git log',
          description: 'Show commit history, most recent first.',
          example: 'git log --oneline --graph --decorate --all',
        },
        {
          command: 'git diff',
          description: 'Show changes between commits, the working tree, and the staging index.',
          example: 'git diff\ngit diff --staged',
        },
      ],
    },
    {
      title: 'Undoing Changes',
      entries: [
        {
          command: 'git stash',
          description: 'Temporarily shelve uncommitted changes so you can work on something else.',
          example: 'git stash\ngit stash pop',
        },
        {
          command: 'git reset',
          description: 'Move the current branch tip and optionally reset the index/working tree.',
          example: 'git reset --soft HEAD~1\ngit reset --hard origin/main',
        },
        {
          command: 'git revert',
          description: 'Create a new commit that undoes the changes introduced by an earlier commit.',
          example: 'git revert abc1234',
        },
      ],
    },
    {
      title: 'Remote Repositories',
      entries: [
        {
          command: 'git push',
          description: 'Upload local commits to a remote repository.',
          example: 'git push origin main',
        },
        {
          command: 'git pull',
          description: 'Fetch from a remote and integrate (merge or rebase) into the current branch.',
          example: 'git pull origin main\ngit pull --rebase',
        },
        {
          command: 'git fetch',
          description: 'Download objects and refs from a remote without merging them.',
          example: 'git fetch origin',
        },
        {
          command: 'git remote',
          description: 'Manage the set of tracked remote repositories.',
          example: 'git remote add origin https://github.com/user/repo.git\ngit remote -v',
        },
      ],
    },
    {
      title: 'Tagging',
      entries: [
        {
          command: 'git tag',
          description: 'Create, list, or delete tags — typically used to mark release versions.',
          example: 'git tag v1.0.0\ngit tag -a v1.0.0 -m "Release 1.0"',
        },
      ],
    },
  ],
}

const regexPage: CheatsheetPage = {
  id: 'regex',
  title: 'Regex Patterns',
  description: 'Common metacharacters, classes, anchors, quantifiers, and groups.',
  sections: [
    {
      title: 'Character Classes',
      entries: [
        {
          command: '.',
          description: 'Matches any single character except a newline (unless dotall mode is on).',
          example: 'a.c matches "abc" and "a1c", not "ac"',
        },
        {
          command: '\\d',
          description: 'Matches any digit, 0-9.',
          example: '\\d{3} matches "123"',
        },
        {
          command: '\\D',
          description: 'Matches any character that is not a digit.',
          example: '\\D+ matches "abc" in "abc123"',
        },
        {
          command: '\\w',
          description: 'Matches a word character: letters, digits, or underscore.',
          example: '\\w+ matches "hello_123"',
        },
        {
          command: '\\W',
          description: 'Matches any character that is not a word character.',
          example: '\\W matches "@" or " "',
        },
        {
          command: '\\s',
          description: 'Matches any whitespace character: space, tab, newline.',
          example: '\\s+ matches "   " (a run of spaces)',
        },
        {
          command: '\\S',
          description: 'Matches any non-whitespace character.',
          example: '\\S+ matches "hello" in "hello world"',
        },
        {
          command: '[...]',
          description: 'Character set: matches any one character listed (or a range) inside the brackets.',
          example: '[aeiou] matches any vowel; [a-z] matches a lowercase letter; [^0-9] matches a non-digit',
        },
      ],
    },
    {
      title: 'Anchors',
      entries: [
        {
          command: '^',
          description: 'Matches the start of the string (or of a line, in multiline mode).',
          example: '^Hello matches "Hello world" only when "Hello" starts the string',
        },
        {
          command: '$',
          description: 'Matches the end of the string (or of a line, in multiline mode).',
          example: 'world$ matches "Hello world" only when "world" ends the string',
        },
        {
          command: '\\b',
          description: 'Matches a word boundary: the position between a word character and a non-word character.',
          example: '\\bcat\\b matches "cat" in "a cat sat", not in "category"',
        },
      ],
    },
    {
      title: 'Quantifiers',
      entries: [
        {
          command: '*',
          description: 'Matches the preceding element zero or more times.',
          example: 'ab*c matches "ac", "abc", "abbbc"',
        },
        {
          command: '+',
          description: 'Matches the preceding element one or more times.',
          example: 'ab+c matches "abc" and "abbc", not "ac"',
        },
        {
          command: '?',
          description: 'Matches the preceding element zero or one time (makes it optional).',
          example: 'colou?r matches both "color" and "colour"',
        },
        {
          command: '{n,m}',
          description: 'Matches the preceding element between n and m times, inclusive.',
          example: '\\d{2,4} matches "12", "123", "1234"',
        },
        {
          command: '*? / +?',
          description: 'Lazy (non-greedy) quantifiers: match as few characters as possible.',
          example: '<.+?> on "<a><b>" matches "<a>", not the whole string',
        },
      ],
    },
    {
      title: 'Groups & Alternation',
      entries: [
        {
          command: '(...)',
          description: 'Capturing group: groups a sub-pattern and captures the matched text.',
          example: '(ab)+ matches "ababab", capturing "ab"',
        },
        {
          command: '(?:...)',
          description: 'Non-capturing group: groups a sub-pattern without creating a capture.',
          example: '(?:ab)+ matches "ababab" with no capture group recorded',
        },
        {
          command: '|',
          description: 'Alternation: matches whatever is on its left or its right.',
          example: 'cat|dog matches "cat" or "dog"',
        },
        {
          command: '(?<name>...)',
          description: 'Named capturing group: captures a sub-match under a readable name.',
          example: '(?<year>\\d{4}) on "2024-01-01" captures group "year" as "2024"',
        },
      ],
    },
    {
      title: 'Lookaround',
      entries: [
        {
          command: '(?=...)',
          description: 'Positive lookahead: matches a position only if followed by the pattern, without consuming it.',
          example: '\\d+(?=px) matches "100" in "100px"',
        },
        {
          command: '(?!...)',
          description: 'Negative lookahead: matches a position only if NOT followed by the pattern.',
          example: '\\d+(?!px) matches "100" in "100em" but not in "100px"',
        },
        {
          command: '(?<=...)',
          description: 'Positive lookbehind: matches a position only if preceded by the pattern.',
          example: '(?<=\\$)\\d+ matches "100" in "\\$100"',
        },
        {
          command: '(?<!...)',
          description: 'Negative lookbehind: matches a position only if NOT preceded by the pattern.',
          example: '(?<!\\$)\\d+ matches "100" in "100 items" but not in "\\$100"',
        },
      ],
    },
  ],
}

const sysctlPage: CheatsheetPage = {
  id: 'sysctl',
  title: 'Linux Sysctl & Kernel Parameters',
  description: 'Real /proc/sys parameter names and what they control.',
  sections: [
    {
      title: 'Network Core (net.core.*)',
      entries: [
        {
          command: 'net.core.somaxconn',
          description: 'Maximum length of the queue of pending (accepted but not yet handled) connections.',
          example: 'net.core.somaxconn = 8192',
        },
        {
          command: 'net.core.rmem_max',
          description: 'Maximum socket receive buffer size, in bytes, for all protocols.',
          example: 'net.core.rmem_max = 67108864',
        },
        {
          command: 'net.core.wmem_max',
          description: 'Maximum socket send buffer size, in bytes, for all protocols.',
          example: 'net.core.wmem_max = 67108864',
        },
        {
          command: 'net.core.default_qdisc',
          description: 'Default queuing discipline for network interfaces. "fq" is recommended alongside BBR.',
          example: 'net.core.default_qdisc = fq',
        },
        {
          command: 'net.core.netdev_max_backlog',
          description: 'Max packets queued on the input side when an interface receives faster than the kernel can process them.',
          example: 'net.core.netdev_max_backlog = 5000',
        },
      ],
    },
    {
      title: 'Network TCP (net.ipv4.*)',
      entries: [
        {
          command: 'net.ipv4.tcp_max_syn_backlog',
          description: 'Maximum number of queued connection requests that have not yet been acknowledged by the client.',
          example: 'net.ipv4.tcp_max_syn_backlog = 8192',
        },
        {
          command: 'net.ipv4.tcp_tw_reuse',
          description: 'Allow reusing sockets in TIME_WAIT state for new outgoing connections.',
          example: 'net.ipv4.tcp_tw_reuse = 1',
        },
        {
          command: 'net.ipv4.tcp_congestion_control',
          description: 'TCP congestion control algorithm. "cubic" is the common default; "bbr" targets high-throughput links.',
          example: 'net.ipv4.tcp_congestion_control = bbr',
        },
        {
          command: 'net.ipv4.tcp_rmem',
          description: 'Three values (min, default, max) for the TCP socket receive buffer, in bytes.',
          example: 'net.ipv4.tcp_rmem = 4096 87380 33554432',
        },
        {
          command: 'net.ipv4.tcp_wmem',
          description: 'Three values (min, default, max) for the TCP socket send buffer, in bytes.',
          example: 'net.ipv4.tcp_wmem = 4096 65536 33554432',
        },
        {
          command: 'net.ipv4.tcp_fin_timeout',
          description: 'Seconds to keep a socket in FIN-WAIT-2 state after the local end has closed it.',
          example: 'net.ipv4.tcp_fin_timeout = 30',
        },
        {
          command: 'net.ipv4.ip_forward',
          description: 'Enables IP forwarding (routing packets between interfaces). Required on routers/gateways.',
          example: 'net.ipv4.ip_forward = 1',
        },
        {
          command: 'net.ipv4.tcp_keepalive_time',
          description: 'Seconds of connection idleness before the kernel starts sending TCP keepalive probes.',
          example: 'net.ipv4.tcp_keepalive_time = 600',
        },
      ],
    },
    {
      title: 'Virtual Memory (vm.*)',
      entries: [
        {
          command: 'vm.swappiness',
          description: 'How aggressively the kernel swaps memory pages to disk, 0-100. Lower favors keeping data in RAM.',
          example: 'vm.swappiness = 10',
        },
        {
          command: 'vm.dirty_ratio',
          description: 'Percentage of RAM that can be filled with dirty (unwritten) pages before writing processes block.',
          example: 'vm.dirty_ratio = 20',
        },
        {
          command: 'vm.dirty_background_ratio',
          description: 'Percentage of RAM with dirty pages at which the kernel starts asynchronous background writeback.',
          example: 'vm.dirty_background_ratio = 10',
        },
        {
          command: 'vm.vfs_cache_pressure',
          description: 'How aggressively the kernel reclaims memory used for directory/inode object caches.',
          example: 'vm.vfs_cache_pressure = 50',
        },
        {
          command: 'vm.overcommit_memory',
          description: 'Controls kernel memory over-commit behavior: 0=heuristic, 1=always allow, 2=never overcommit.',
          example: 'vm.overcommit_memory = 1',
        },
      ],
    },
    {
      title: 'File System (fs.*)',
      entries: [
        {
          command: 'fs.file-max',
          description: 'System-wide maximum number of open file handles.',
          example: 'fs.file-max = 2097152',
        },
        {
          command: 'fs.inotify.max_user_watches',
          description: 'Maximum number of files a single user can watch via inotify (editors, build tools, file watchers).',
          example: 'fs.inotify.max_user_watches = 524288',
        },
      ],
    },
    {
      title: 'Kernel (kernel.*)',
      entries: [
        {
          command: 'kernel.pid_max',
          description: 'Maximum process ID value the kernel will assign.',
          example: 'kernel.pid_max = 4194304',
        },
        {
          command: 'kernel.panic',
          description: 'Seconds to wait before automatically rebooting after a kernel panic. 0 disables auto-reboot.',
          example: 'kernel.panic = 10',
        },
      ],
    },
  ],
}

const crontabPage: CheatsheetPage = {
  id: 'crontab',
  title: 'Crontab Syntax',
  description: 'The 5-field schedule format, special characters, shortcuts, and worked examples.',
  sections: [
    {
      title: 'The 5 Fields (minute hour day month weekday)',
      entries: [
        {
          command: 'minute',
          description: 'Field 1. Valid values: 0-59.',
          example: '30 * * * * runs at the 30th minute of every hour',
        },
        {
          command: 'hour',
          description: 'Field 2. Valid values: 0-23.',
          example: '0 9 * * * runs at 9:00 AM every day',
        },
        {
          command: 'day of month',
          description: 'Field 3. Valid values: 1-31.',
          example: '0 0 1 * * runs at midnight on the 1st of every month',
        },
        {
          command: 'month',
          description: 'Field 4. Valid values: 1-12, or names Jan-Dec.',
          example: '0 0 1 6 * runs at midnight on June 1st',
        },
        {
          command: 'day of week',
          description: 'Field 5. Valid values: 0-7 (0 and 7 both mean Sunday), or names Sun-Sat.',
          example: '0 0 * * 1 runs at midnight every Monday',
        },
      ],
    },
    {
      title: 'Special Characters',
      entries: [
        {
          command: '*',
          description: 'Matches every possible value for the field ("any").',
          example: '* * * * * runs every minute',
        },
        {
          command: ',',
          description: 'Value list separator: run at each listed value.',
          example: '0,15,30,45 * * * * runs at :00, :15, :30, and :45 of every hour',
        },
        {
          command: '-',
          description: 'Range of values, inclusive.',
          example: '0 9-17 * * * runs at the top of every hour from 9am through 5pm',
        },
        {
          command: '/',
          description: 'Step values: run every Nth value within a range (or within the full field range).',
          example: '*/15 * * * * runs every 15 minutes',
        },
      ],
    },
    {
      title: 'Nickname Shortcuts',
      entries: [
        {
          command: '@reboot',
          description: 'Run once, at system startup.',
          example: '@reboot /path/to/script.sh',
        },
        {
          command: '@yearly / @annually',
          description: 'Run once a year. Equivalent to "0 0 1 1 *".',
          example: '@yearly /path/to/script.sh',
        },
        {
          command: '@monthly',
          description: 'Run once a month. Equivalent to "0 0 1 * *".',
          example: '@monthly /path/to/script.sh',
        },
        {
          command: '@weekly',
          description: 'Run once a week. Equivalent to "0 0 * * 0".',
          example: '@weekly /path/to/script.sh',
        },
        {
          command: '@daily / @midnight',
          description: 'Run once a day. Equivalent to "0 0 * * *".',
          example: '@daily /path/to/script.sh',
        },
        {
          command: '@hourly',
          description: 'Run once an hour. Equivalent to "0 * * * *".',
          example: '@hourly /path/to/script.sh',
        },
      ],
    },
    {
      title: 'Worked Examples',
      entries: [
        {
          command: 'Every 15 minutes',
          description: 'Run a job four times per hour, on the quarter hour.',
          example: '*/15 * * * * /path/to/script.sh',
        },
        {
          command: 'Every weekday at 9am',
          description: 'Run once a day, Monday through Friday only.',
          example: '0 9 * * 1-5 /path/to/script.sh',
        },
        {
          command: 'Every Sunday at midnight',
          description: 'A typical weekly backup schedule.',
          example: '0 0 * * 0 /path/to/backup.sh',
        },
        {
          command: 'First day of every month at 3am',
          description: 'A typical monthly maintenance/report schedule.',
          example: '0 3 1 * * /path/to/script.sh',
        },
        {
          command: 'Every 5 minutes, business hours, weekdays',
          description: 'Combines a step value, an hour range, and a weekday range.',
          example: '*/5 9-17 * * 1-5 /path/to/script.sh',
        },
        {
          command: 'Twice a day at 6am and 6pm',
          description: 'Combines a value list in the hour field.',
          example: '0 6,18 * * * /path/to/script.sh',
        },
      ],
    },
  ],
}

const chmodPage: CheatsheetPage = {
  id: 'chmod',
  title: 'Chmod Permissions',
  description: 'The octal digit -> rwx mapping and common permission combinations.',
  sections: [
    {
      title: 'Octal Digit -> rwx',
      entries: [
        {
          command: '0',
          description: 'No permissions.',
          example: '--- ',
        },
        {
          command: '1',
          description: 'Execute only.',
          example: '--x',
        },
        {
          command: '2',
          description: 'Write only.',
          example: '-w-',
        },
        {
          command: '3',
          description: 'Write and execute.',
          example: '-wx',
        },
        {
          command: '4',
          description: 'Read only.',
          example: 'r--',
        },
        {
          command: '5',
          description: 'Read and execute.',
          example: 'r-x',
        },
        {
          command: '6',
          description: 'Read and write.',
          example: 'rw-',
        },
        {
          command: '7',
          description: 'Read, write, and execute (full control).',
          example: 'rwx',
        },
      ],
    },
    {
      title: 'How the Three Digits Work',
      entries: [
        {
          command: '1st digit',
          description: 'Permissions for the file\'s owner (user).',
          example: 'chmod 7__ file  → owner gets rwx',
        },
        {
          command: '2nd digit',
          description: 'Permissions for the file\'s group.',
          example: 'chmod _5_ file  → group gets r-x',
        },
        {
          command: '3rd digit',
          description: 'Permissions for everyone else (other/world).',
          example: 'chmod __4 file  → other gets r--',
        },
      ],
    },
    {
      title: 'Common Combinations',
      entries: [
        {
          command: '644',
          description: 'rw-r--r--  Owner reads/writes; group and others read-only. The default for regular files (configs, text, HTML).',
          example: 'chmod 644 file.txt',
        },
        {
          command: '755',
          description: 'rwxr-xr-x  Owner has full control; group and others can read and execute. Standard for scripts and directories.',
          example: 'chmod 755 script.sh',
        },
        {
          command: '600',
          description: 'rw-------  Owner reads/writes; nobody else has any access. Common for private config/secret files.',
          example: 'chmod 600 .env',
        },
        {
          command: '700',
          description: 'rwx------  Owner has full control; nobody else has any access. Common for private scripts and directories.',
          example: 'chmod 700 ~/.ssh',
        },
        {
          command: '400',
          description: 'r--------  Owner read-only; nobody else has any access. Used for sensitive read-only files like SSH private keys.',
          example: 'chmod 400 id_rsa',
        },
        {
          command: '750',
          description: 'rwxr-x---  Owner has full control; group can read/execute; others have no access. Typical for group-shared scripts.',
          example: 'chmod 750 deploy.sh',
        },
        {
          command: '666',
          description: 'rw-rw-rw-  Everyone can read and write, nobody can execute. Rarely appropriate outside temp/shared scratch files.',
          example: 'chmod 666 shared_scratch.log',
        },
        {
          command: '777',
          description: 'rwxrwxrwx  Everyone has full control. Almost never the right answer in production — a common security anti-pattern.',
          example: 'chmod 777 file  # avoid — grants world write+execute',
        },
      ],
    },
  ],
}

const httpStatusPage: CheatsheetPage = {
  id: 'http-status',
  title: 'HTTP Status Codes',
  description: 'The status codes that actually show up in production, grouped by class.',
  sections: [
    {
      title: '1xx — Informational',
      entries: [
        {
          command: '100',
          description: 'Continue — client should proceed with the request body.',
          example: 'Sent before a large POST body',
        },
        {
          command: '101',
          description: 'Switching Protocols — server is switching per the client\'s Upgrade header.',
          example: 'HTTP → WebSocket upgrade',
        },
      ],
    },
    {
      title: '2xx — Success',
      entries: [
        {
          command: '200',
          description: 'OK — the standard successful response.',
          example: 'GET /users/1 → 200',
        },
        {
          command: '201',
          description: 'Created — a new resource was created.',
          example: 'POST /users → 201 Location: /users/42',
        },
        {
          command: '202',
          description: 'Accepted — request accepted for async processing, not yet complete.',
          example: 'Queued a background job',
        },
        {
          command: '204',
          description: 'No Content — success, no response body.',
          example: 'DELETE /users/1 → 204',
        },
        {
          command: '206',
          description: 'Partial Content — response to a Range request.',
          example: 'Resumable file download',
        },
      ],
    },
    {
      title: '3xx — Redirection',
      entries: [
        {
          command: '301',
          description: 'Moved Permanently — resource has a new permanent URL; clients should update links.',
          example: 'http:// → https:// redirect',
        },
        {
          command: '302',
          description: 'Found — temporary redirect (historically often misused for what 303 means).',
          example: 'Post-login redirect',
        },
        {
          command: '303',
          description: 'See Other — redirect after a POST; client should GET the new URL.',
          example: 'POST /orders → 303 /orders/42',
        },
        {
          command: '304',
          description: 'Not Modified — cached response is still valid.',
          example: 'Conditional GET with If-None-Match',
        },
        {
          command: '307',
          description: 'Temporary Redirect — like 302, but the method/body must NOT change.',
          example: 'Redirecting a POST without turning it into a GET',
        },
        {
          command: '308',
          description: 'Permanent Redirect — like 301, but the method/body must NOT change.',
          example: 'API endpoint moved, same verb required',
        },
      ],
    },
    {
      title: '4xx — Client Error',
      entries: [
        {
          command: '400',
          description: 'Bad Request — malformed request syntax or invalid parameters.',
          example: 'Invalid JSON body',
        },
        {
          command: '401',
          description: 'Unauthorized — authentication is required or has failed.',
          example: 'Missing/expired Bearer token',
        },
        {
          command: '403',
          description: 'Forbidden — authenticated, but not allowed to access this resource.',
          example: 'Valid token, wrong role',
        },
        {
          command: '404',
          description: 'Not Found — no resource at this URL.',
          example: 'GET /users/999999',
        },
        {
          command: '405',
          description: 'Method Not Allowed — the URL exists but not for this HTTP method.',
          example: 'DELETE on a read-only endpoint',
        },
        {
          command: '408',
          description: 'Request Timeout — server gave up waiting for the request.',
          example: 'Slow client, idle connection',
        },
        {
          command: '409',
          description: 'Conflict — request conflicts with current server state.',
          example: 'Optimistic-lock version mismatch',
        },
        {
          command: '410',
          description: 'Gone — resource existed but was permanently removed.',
          example: 'Deleted API version',
        },
        {
          command: '413',
          description: 'Payload Too Large — request body exceeds server limits.',
          example: 'Upload bigger than nginx client_max_body_size',
        },
        {
          command: '414',
          description: 'URI Too Long.',
          example: 'Excessively long query string',
        },
        {
          command: '415',
          description: 'Unsupported Media Type — Content-Type not accepted by the server.',
          example: 'Sending XML to a JSON-only API',
        },
        {
          command: '418',
          description: 'I\'m a Teapot — an April Fools\' joke from RFC 2324, still occasionally implemented for fun.',
          example: 'Not meant to appear in real APIs',
        },
        {
          command: '422',
          description: 'Unprocessable Entity — syntactically valid but semantically invalid (failed validation).',
          example: 'Required field missing after JSON parses fine',
        },
        {
          command: '425',
          description: 'Too Early — server unwilling to risk processing a replayable early-data request.',
          example: 'TLS 1.3 0-RTT request',
        },
        {
          command: '429',
          description: 'Too Many Requests — rate limit exceeded.',
          example: 'API throttling, check Retry-After header',
        },
        {
          command: '431',
          description: 'Request Header Fields Too Large.',
          example: 'Oversized cookies/auth headers',
        },
        {
          command: '451',
          description: 'Unavailable For Legal Reasons.',
          example: 'Content blocked by court order/DMCA',
        },
      ],
    },
    {
      title: '5xx — Server Error',
      entries: [
        {
          command: '500',
          description: 'Internal Server Error — generic unhandled server-side failure.',
          example: 'Unhandled exception in application code',
        },
        {
          command: '501',
          description: 'Not Implemented — server doesn\'t support the requested functionality.',
          example: 'Unsupported HTTP method entirely',
        },
        {
          command: '502',
          description: 'Bad Gateway — upstream server returned an invalid response.',
          example: 'nginx reverse proxy, backend crashed mid-request',
        },
        {
          command: '503',
          description: 'Service Unavailable — server temporarily can\'t handle the request (overload/maintenance).',
          example: 'Deploy in progress, health check failing',
        },
        {
          command: '504',
          description: 'Gateway Timeout — upstream server didn\'t respond in time.',
          example: 'Backend request exceeded proxy timeout',
        },
        {
          command: '505',
          description: 'HTTP Version Not Supported.',
          example: 'Client requested an unsupported HTTP version',
        },
        {
          command: '507',
          description: 'Insufficient Storage (WebDAV) — server out of space to complete the request.',
          example: 'Disk full on write',
        },
        {
          command: '511',
          description: 'Network Authentication Required — client must authenticate to gain network access.',
          example: 'Captive portal (hotel/airport WiFi)',
        },
      ],
    },
  ],
}

const commonPortsPage: CheatsheetPage = {
  id: 'common-ports',
  title: 'Common Ports',
  description: 'Well-known service ports an SRE runs into daily, grouped by category.',
  sections: [
    {
      title: 'Web',
      entries: [
        {
          command: '80/tcp',
          description: 'HTTP.',
          example: 'Plaintext web traffic',
        },
        {
          command: '443/tcp',
          description: 'HTTPS.',
          example: 'TLS-encrypted web traffic',
        },
        {
          command: '3000/tcp',
          description: 'Common dev-server default (Node/Rails/many frameworks).',
          example: 'npm run dev',
        },
        {
          command: '8080/tcp',
          description: 'Common alt-HTTP / app server port.',
          example: 'Tomcat, many reverse-proxied apps',
        },
        {
          command: '8443/tcp',
          description: 'Common alt-HTTPS port.',
          example: 'Admin UIs behind a proxy',
        },
      ],
    },
    {
      title: 'Mail',
      entries: [
        {
          command: '25/tcp',
          description: 'SMTP — mail relay between servers.',
          example: 'MTA-to-MTA delivery',
        },
        {
          command: '465/tcp',
          description: 'SMTPS — SMTP submission over implicit TLS.',
          example: 'Client-to-server submission',
        },
        {
          command: '587/tcp',
          description: 'SMTP Submission — mail client to server, with STARTTLS.',
          example: 'Standard mail client config port',
        },
        {
          command: '110/tcp',
          description: 'POP3.',
          example: 'Legacy mail retrieval',
        },
        {
          command: '995/tcp',
          description: 'POP3S — POP3 over implicit TLS.',
          example: 'Encrypted POP3',
        },
        {
          command: '143/tcp',
          description: 'IMAP.',
          example: 'Mail retrieval, server-side folders',
        },
        {
          command: '993/tcp',
          description: 'IMAPS — IMAP over implicit TLS.',
          example: 'Encrypted IMAP',
        },
      ],
    },
    {
      title: 'Databases',
      entries: [
        {
          command: '3306/tcp',
          description: 'MySQL / MariaDB.',
          example: 'mysql -h host -P 3306',
        },
        {
          command: '5432/tcp',
          description: 'PostgreSQL.',
          example: 'psql -h host -p 5432',
        },
        {
          command: '6379/tcp',
          description: 'Redis.',
          example: 'redis-cli -h host -p 6379',
        },
        {
          command: '27017/tcp',
          description: 'MongoDB.',
          example: 'mongosh host:27017',
        },
        {
          command: '1521/tcp',
          description: 'Oracle Database (default listener).',
          example: 'TNS listener',
        },
      ],
    },
    {
      title: 'Remote Access',
      entries: [
        {
          command: '22/tcp',
          description: 'SSH — also used for SFTP and git-over-SSH.',
          example: 'ssh user@host',
        },
        {
          command: '3389/tcp',
          description: 'RDP — Windows Remote Desktop.',
          example: 'mstsc /v:host',
        },
        {
          command: '5900/tcp',
          description: 'VNC.',
          example: 'VNC viewer default',
        },
      ],
    },
    {
      title: 'Infrastructure & Monitoring',
      entries: [
        {
          command: '53/tcp+udp',
          description: 'DNS — TCP for zone transfers/large responses, UDP for normal queries.',
          example: 'dig @host, named/bind9',
        },
        {
          command: '123/udp',
          description: 'NTP — time synchronization.',
          example: 'chronyd/ntpd',
        },
        {
          command: '161/udp',
          description: 'SNMP — polling.',
          example: 'snmpwalk host',
        },
        {
          command: '162/udp',
          description: 'SNMP Trap — async notifications.',
          example: 'Trap receiver listener',
        },
        {
          command: '389/tcp',
          description: 'LDAP.',
          example: 'Directory bind/query',
        },
        {
          command: '636/tcp',
          description: 'LDAPS — LDAP over implicit TLS.',
          example: 'Encrypted directory bind',
        },
        {
          command: '111/tcp+udp',
          description: 'rpcbind/portmapper — required alongside NFS.',
          example: 'showmount -e host',
        },
        {
          command: '2049/tcp+udp',
          description: 'NFS.',
          example: 'mount -t nfs host:/export /mnt',
        },
        {
          command: '5672/tcp',
          description: 'AMQP — RabbitMQ default.',
          example: 'Message broker connections',
        },
        {
          command: '9092/tcp',
          description: 'Kafka broker.',
          example: 'Producer/consumer connections',
        },
        {
          command: '2379/tcp',
          description: 'etcd client API.',
          example: 'etcdctl --endpoints host:2379',
        },
        {
          command: '2380/tcp',
          description: 'etcd peer (cluster) API.',
          example: 'etcd member-to-member traffic',
        },
        {
          command: '6443/tcp',
          description: 'Kubernetes API server.',
          example: 'kubectl talks here',
        },
        {
          command: '10250/tcp',
          description: 'Kubelet API.',
          example: 'Node agent, exec/logs traffic',
        },
        {
          command: '9090/tcp',
          description: 'Prometheus (also a common generic app port — check context).',
          example: 'Prometheus web UI/API',
        },
        {
          command: '9100/tcp',
          description: 'Prometheus node_exporter.',
          example: 'Host metrics scrape target',
        },
      ],
    },
  ],
}

const dockerPage: CheatsheetPage = {
  id: 'docker',
  title: 'Docker Commands',
  description: 'Image and container lifecycle, volumes, networks, and Compose basics.',
  sections: [
    {
      title: 'Images',
      entries: [
        {
          command: 'docker build',
          description: 'Build an image from a Dockerfile in the current directory.',
          example: 'docker build -t myapp:1.0 .',
        },
        {
          command: 'docker images',
          description: 'List locally stored images.',
          example: 'docker images',
        },
        {
          command: 'docker pull',
          description: 'Download an image from a registry.',
          example: 'docker pull nginx:alpine',
        },
        {
          command: 'docker push',
          description: 'Upload an image to a registry.',
          example: 'docker push myrepo/myapp:1.0',
        },
        {
          command: 'docker rmi',
          description: 'Remove one or more images.',
          example: 'docker rmi myapp:1.0',
        },
        {
          command: 'docker tag',
          description: 'Create an additional tag for an existing image.',
          example: 'docker tag myapp:1.0 myapp:latest',
        },
      ],
    },
    {
      title: 'Containers',
      entries: [
        {
          command: 'docker run',
          description: 'Create and start a container from an image.',
          example: 'docker run -d -p 8080:80 --name web nginx',
        },
        {
          command: 'docker ps',
          description: 'List running containers (-a for all, including stopped).',
          example: 'docker ps -a',
        },
        {
          command: 'docker exec',
          description: 'Run a command inside a running container.',
          example: 'docker exec -it web sh',
        },
        {
          command: 'docker logs',
          description: 'Show a container\'s stdout/stderr (-f to follow).',
          example: 'docker logs -f web',
        },
        {
          command: 'docker stop / start / restart',
          description: 'Stop, start, or restart a container by name or ID.',
          example: 'docker stop web',
        },
        {
          command: 'docker rm',
          description: 'Remove a stopped container.',
          example: 'docker rm web',
        },
        {
          command: 'docker inspect',
          description: 'Show low-level JSON details (IP, mounts, env) for a container or image.',
          example: 'docker inspect web',
        },
      ],
    },
    {
      title: 'Volumes & Networks',
      entries: [
        {
          command: 'docker volume create/ls/rm',
          description: 'Manage named volumes for persistent data.',
          example: 'docker volume create dbdata',
        },
        {
          command: '-v host:container',
          description: 'Bind-mount a host path into the container.',
          example: 'docker run -v /srv/data:/data nginx',
        },
        {
          command: 'docker network create/ls/rm',
          description: 'Manage user-defined bridge networks so containers can resolve each other by name.',
          example: 'docker network create appnet',
        },
      ],
    },
    {
      title: 'Compose',
      entries: [
        {
          command: 'docker compose up -d',
          description: 'Create and start all services defined in docker-compose.yml, detached.',
          example: 'docker compose up -d',
        },
        {
          command: 'docker compose down',
          description: 'Stop and remove containers, networks created by up (-v also removes volumes).',
          example: 'docker compose down -v',
        },
        {
          command: 'docker compose logs -f',
          description: 'Follow logs across all services.',
          example: 'docker compose logs -f web',
        },
        {
          command: 'docker compose ps',
          description: 'List the services and their status.',
          example: 'docker compose ps',
        },
      ],
    },
    {
      title: 'Cleanup',
      entries: [
        {
          command: 'docker system prune',
          description: 'Remove stopped containers, dangling images, unused networks (-a for all unused images too).',
          example: 'docker system prune -a',
        },
        {
          command: 'docker container prune',
          description: 'Remove all stopped containers.',
          example: 'docker container prune',
        },
      ],
    },
  ],
}

const terraformPage: CheatsheetPage = {
  id: 'terraform',
  title: 'Terraform Commands',
  description: 'Core workflow, state management, and workspaces.',
  sections: [
    {
      title: 'Core Workflow',
      entries: [
        {
          command: 'terraform init',
          description: 'Download providers/modules and set up the backend.',
          example: 'terraform init',
        },
        {
          command: 'terraform plan',
          description: 'Show what would change without applying it.',
          example: 'terraform plan -out=tfplan',
        },
        {
          command: 'terraform apply',
          description: 'Apply changes to reach the desired state.',
          example: 'terraform apply tfplan',
        },
        {
          command: 'terraform destroy',
          description: 'Destroy every resource this configuration manages.',
          example: 'terraform destroy',
        },
        {
          command: 'terraform fmt',
          description: 'Rewrite .tf files to canonical style.',
          example: 'terraform fmt -recursive',
        },
        {
          command: 'terraform validate',
          description: 'Check configuration syntax and internal consistency.',
          example: 'terraform validate',
        },
      ],
    },
    {
      title: 'State',
      entries: [
        {
          command: 'terraform state list',
          description: 'List every resource tracked in the current state.',
          example: 'terraform state list',
        },
        {
          command: 'terraform state show',
          description: 'Show the tracked attributes of one resource.',
          example: 'terraform state show aws_instance.web',
        },
        {
          command: 'terraform state mv',
          description: 'Rename a resource in state without destroying/recreating it.',
          example: 'terraform state mv aws_instance.old aws_instance.new',
        },
        {
          command: 'terraform state rm',
          description: 'Stop tracking a resource without destroying it.',
          example: 'terraform state rm aws_instance.web',
        },
        {
          command: 'terraform import',
          description: 'Bring an existing, unmanaged resource under Terraform management.',
          example: 'terraform import aws_instance.web i-0123456789',
        },
      ],
    },
    {
      title: 'Workspaces & Variables',
      entries: [
        {
          command: 'terraform workspace new/list/select',
          description: 'Manage isolated state files (e.g. dev/staging/prod) from one configuration.',
          example: 'terraform workspace select prod',
        },
        {
          command: '-var / -var-file',
          description: 'Pass a variable value or a whole tfvars file on the command line.',
          example: 'terraform apply -var-file=prod.tfvars',
        },
        {
          command: 'terraform output',
          description: 'Print the values of declared outputs.',
          example: 'terraform output -json',
        },
      ],
    },
  ],
}

const ansiblePage: CheatsheetPage = {
  id: 'ansible',
  title: 'Ansible Commands',
  description: 'Ad-hoc modules, playbook runs, inventory, and vault.',
  sections: [
    {
      title: 'Ad-hoc Commands',
      entries: [
        {
          command: 'ansible all -m ping',
          description: 'Check connectivity to every host in the inventory.',
          example: 'ansible all -i inventory.ini -m ping',
        },
        {
          command: 'ansible <group> -m shell -a',
          description: 'Run a shell command against a host group.',
          example: 'ansible web -m shell -a \'uptime\'',
        },
        {
          command: 'ansible <group> -m copy -a',
          description: 'Copy a file to remote hosts.',
          example: 'ansible web -m copy -a \'src=app.conf dest=/etc/app.conf\'',
        },
        {
          command: 'ansible <group> -m apt/yum -a',
          description: 'Install a package on remote hosts.',
          example: 'ansible web -m apt -a \'name=nginx state=present\' --become',
        },
      ],
    },
    {
      title: 'Playbooks',
      entries: [
        {
          command: 'ansible-playbook',
          description: 'Run a playbook against the inventory.',
          example: 'ansible-playbook site.yml',
        },
        {
          command: '--check',
          description: 'Dry-run: report what would change without making changes.',
          example: 'ansible-playbook site.yml --check --diff',
        },
        {
          command: '--limit',
          description: 'Restrict a run to a subset of hosts/groups.',
          example: 'ansible-playbook site.yml --limit web01',
        },
        {
          command: '--tags / --skip-tags',
          description: 'Run (or skip) only tasks with matching tags.',
          example: 'ansible-playbook site.yml --tags deploy',
        },
        {
          command: '-K / --ask-become-pass',
          description: 'Prompt for the sudo/become password.',
          example: 'ansible-playbook site.yml -K',
        },
      ],
    },
    {
      title: 'Inventory',
      entries: [
        {
          command: '-i inventory.ini',
          description: 'Point at a specific inventory file (default is /etc/ansible/hosts).',
          example: 'ansible-playbook -i hosts.ini site.yml',
        },
        {
          command: 'ansible-inventory --list',
          description: 'Print the resolved inventory as JSON, including dynamic inventory sources.',
          example: 'ansible-inventory -i aws_ec2.yml --list',
        },
      ],
    },
    {
      title: 'Vault',
      entries: [
        {
          command: 'ansible-vault create',
          description: 'Create a new encrypted file.',
          example: 'ansible-vault create secrets.yml',
        },
        {
          command: 'ansible-vault edit',
          description: 'Edit an existing encrypted file in place.',
          example: 'ansible-vault edit secrets.yml',
        },
        {
          command: 'ansible-vault view',
          description: 'Print a decrypted file to stdout without writing it out.',
          example: 'ansible-vault view secrets.yml',
        },
        {
          command: '--vault-password-file',
          description: 'Supply the vault password non-interactively.',
          example: 'ansible-playbook site.yml --vault-password-file=.vault_pass',
        },
      ],
    },
  ],
}

const kubernetesPage: CheatsheetPage = {
  id: 'kubernetes',
  title: 'Kubernetes (kubectl) Commands',
  description: 'Everyday kubectl commands for inspecting and changing a cluster.',
  sections: [
    {
      title: 'Inspecting Resources',
      entries: [
        {
          command: 'kubectl get',
          description: 'List resources of a given kind.',
          example: 'kubectl get pods -n prod -o wide',
        },
        {
          command: 'kubectl describe',
          description: 'Show detailed state and recent events for one resource.',
          example: 'kubectl describe pod web-abc123',
        },
        {
          command: 'kubectl logs',
          description: 'Show a container\'s logs (-f to follow, -p for the previous crashed instance).',
          example: 'kubectl logs -f web-abc123 -c app',
        },
        {
          command: 'kubectl get events',
          description: 'List cluster events sorted by time, useful for debugging scheduling failures.',
          example: 'kubectl get events --sort-by=.lastTimestamp',
        },
      ],
    },
    {
      title: 'Changing State',
      entries: [
        {
          command: 'kubectl apply -f',
          description: 'Create or update resources from a manifest file/directory.',
          example: 'kubectl apply -f deployment.yaml',
        },
        {
          command: 'kubectl delete',
          description: 'Delete a resource by name or by manifest.',
          example: 'kubectl delete -f deployment.yaml',
        },
        {
          command: 'kubectl scale',
          description: 'Change a Deployment/ReplicaSet\'s replica count.',
          example: 'kubectl scale deployment web --replicas=5',
        },
        {
          command: 'kubectl rollout status/undo',
          description: 'Watch or roll back a Deployment rollout.',
          example: 'kubectl rollout undo deployment/web',
        },
        {
          command: 'kubectl edit',
          description: 'Open a live resource in $EDITOR and apply the diff on save.',
          example: 'kubectl edit deployment web',
        },
      ],
    },
    {
      title: 'Interacting with Pods',
      entries: [
        {
          command: 'kubectl exec',
          description: 'Run a command inside a running container.',
          example: 'kubectl exec -it web-abc123 -- sh',
        },
        {
          command: 'kubectl port-forward',
          description: 'Forward a local port to a port on a pod/service.',
          example: 'kubectl port-forward svc/web 8080:80',
        },
        {
          command: 'kubectl cp',
          description: 'Copy files between a pod and the local filesystem.',
          example: 'kubectl cp web-abc123:/var/log/app.log ./app.log',
        },
      ],
    },
    {
      title: 'Contexts & Namespaces',
      entries: [
        {
          command: 'kubectl config get-contexts',
          description: 'List known clusters/contexts from kubeconfig.',
          example: 'kubectl config get-contexts',
        },
        {
          command: 'kubectl config use-context',
          description: 'Switch the active cluster context.',
          example: 'kubectl config use-context prod-cluster',
        },
        {
          command: '-n / --namespace',
          description: 'Scope a command to one namespace instead of default.',
          example: 'kubectl get pods -n kube-system',
        },
      ],
    },
  ],
}

const powershellPage: CheatsheetPage = {
  id: 'powershell',
  title: 'Windows PowerShell Commands',
  description: 'Navigation, file, process/service, and remoting cmdlets.',
  sections: [
    {
      title: 'Navigation & Files',
      entries: [
        {
          command: 'Get-ChildItem (gci, ls, dir)',
          description: 'List items in a directory.',
          example: 'Get-ChildItem -Recurse -Filter *.log',
        },
        {
          command: 'Get-Content (gc, cat)',
          description: 'Read a file\'s contents (-Tail for the last N lines).',
          example: 'Get-Content app.log -Tail 50 -Wait',
        },
        {
          command: 'Set-Location (cd)',
          description: 'Change the current directory.',
          example: 'Set-Location C:\\inetpub',
        },
        {
          command: 'Copy-Item / Move-Item / Remove-Item',
          description: 'Copy, move, or delete files and directories.',
          example: 'Remove-Item -Recurse -Force .\\temp',
        },
        {
          command: 'New-Item',
          description: 'Create a file, directory, or symlink.',
          example: 'New-Item -ItemType Directory -Path C:\\data',
        },
      ],
    },
    {
      title: 'Processes & Services',
      entries: [
        {
          command: 'Get-Process (ps)',
          description: 'List running processes.',
          example: 'Get-Process | Sort-Object CPU -Descending',
        },
        {
          command: 'Stop-Process',
          description: 'Kill a process by name or ID.',
          example: 'Stop-Process -Name notepad -Force',
        },
        {
          command: 'Get-Service',
          description: 'List Windows services and their status.',
          example: 'Get-Service | Where-Object Status -eq \'Running\'',
        },
        {
          command: 'Start-Service / Stop-Service / Restart-Service',
          description: 'Control a Windows service.',
          example: 'Restart-Service -Name W32Time',
        },
      ],
    },
    {
      title: 'Pipeline Basics',
      entries: [
        {
          command: 'Where-Object (?)',
          description: 'Filter pipeline objects by a condition.',
          example: 'Get-Process | Where-Object { $_.CPU -gt 50 }',
        },
        {
          command: 'Select-Object (select)',
          description: 'Pick specific properties, or the first/last N objects.',
          example: 'Get-Process | Select-Object -First 5 Name, CPU',
        },
        {
          command: 'ForEach-Object (%)',
          description: 'Run a script block once per pipeline object.',
          example: 'Get-ChildItem | ForEach-Object { $_.Name }',
        },
        {
          command: 'Sort-Object',
          description: 'Sort pipeline objects by one or more properties.',
          example: 'Get-Process | Sort-Object WS -Descending',
        },
      ],
    },
    {
      title: 'Remoting & Modules',
      entries: [
        {
          command: 'Enter-PSSession',
          description: 'Open an interactive remote session over WinRM.',
          example: 'Enter-PSSession -ComputerName SRV01',
        },
        {
          command: 'Invoke-Command',
          description: 'Run a script block on one or more remote computers.',
          example: 'Invoke-Command -ComputerName SRV01,SRV02 -ScriptBlock { Get-Service }',
        },
        {
          command: 'Get-Help',
          description: 'Show a cmdlet\'s documentation (-Examples, -Full).',
          example: 'Get-Help Get-Service -Examples',
        },
        {
          command: 'Import-Module',
          description: 'Load a module\'s cmdlets into the current session.',
          example: 'Import-Module ActiveDirectory',
        },
      ],
    },
  ],
}

const windowsCmdPage: CheatsheetPage = {
  id: 'windows-cmd',
  title: 'Windows CMD Commands',
  description: 'Classic cmd.exe commands for networking, processes, and the registry.',
  sections: [
    {
      title: 'Files & Navigation',
      entries: [
        {
          command: 'dir',
          description: 'List directory contents.',
          example: 'dir /s *.log',
        },
        {
          command: 'cd',
          description: 'Change or print the current directory.',
          example: 'cd \\inetpub\\logs',
        },
        {
          command: 'copy / xcopy / robocopy',
          description: 'Copy files; robocopy handles large trees with retry/logging.',
          example: 'robocopy C:\\src D:\\dst /MIR',
        },
        {
          command: 'del / rmdir',
          description: 'Delete a file or a directory (/s for recursive).',
          example: 'rmdir /s /q C:\\temp',
        },
      ],
    },
    {
      title: 'Networking',
      entries: [
        {
          command: 'ipconfig',
          description: 'Show IP configuration (/all for full detail, /flushdns to clear the resolver cache).',
          example: 'ipconfig /all',
        },
        {
          command: 'netstat',
          description: 'Show active connections and listening ports.',
          example: 'netstat -ano | findstr :443',
        },
        {
          command: 'ping / tracert',
          description: 'Test reachability, or trace the route to a host.',
          example: 'tracert 8.8.8.8',
        },
        {
          command: 'nslookup',
          description: 'Query DNS for a name or record.',
          example: 'nslookup example.com',
        },
      ],
    },
    {
      title: 'Processes & Services',
      entries: [
        {
          command: 'tasklist',
          description: 'List running processes (/svc to show hosted services).',
          example: 'tasklist /svc',
        },
        {
          command: 'taskkill',
          description: 'Terminate a process by PID or image name.',
          example: 'taskkill /PID 4832 /F',
        },
        {
          command: 'sc query / sc start / sc stop',
          description: 'Query or control a Windows service.',
          example: 'sc query w32time',
        },
      ],
    },
    {
      title: 'System & Registry',
      entries: [
        {
          command: 'systeminfo',
          description: 'Print OS version, patch level, and hardware summary.',
          example: 'systeminfo',
        },
        {
          command: 'reg query / reg add',
          description: 'Read or write a registry key/value.',
          example: 'reg query HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion',
        },
        {
          command: 'whoami /all',
          description: 'Show the current user, groups, and privileges.',
          example: 'whoami /all',
        },
      ],
    },
  ],
}

const linuxCommandsPage: CheatsheetPage = {
  id: 'linux-commands',
  title: 'Linux Commands',
  description: 'General-purpose shell commands for files, processes, permissions, and inspection — see the Sysctl page for kernel tuning specifically.',
  sections: [
    {
      title: 'Files & Directories',
      entries: [
        {
          command: 'ls -la',
          description: 'List files including hidden ones, with permissions/owner/size.',
          example: 'ls -la /etc',
        },
        {
          command: 'find',
          description: 'Search a directory tree by name, type, size, or age.',
          example: 'find /var/log -name \'*.log\' -mtime +7',
        },
        {
          command: 'grep -rn',
          description: 'Recursively search file contents, printing line numbers.',
          example: 'grep -rn \'ERROR\' /var/log/app',
        },
        {
          command: 'tar',
          description: 'Create or extract a tar archive (-czf create gzip, -xzf extract).',
          example: 'tar -xzf app.tar.gz -C /opt/app',
        },
        {
          command: 'ln -s',
          description: 'Create a symbolic link.',
          example: 'ln -s /opt/app/current /opt/app/latest',
        },
      ],
    },
    {
      title: 'Processes',
      entries: [
        {
          command: 'ps aux',
          description: 'List every running process with owner, CPU, and memory.',
          example: 'ps aux | grep nginx',
        },
        {
          command: 'top / htop',
          description: 'Live view of process activity and resource usage.',
          example: 'top',
        },
        {
          command: 'kill / kill -9',
          description: 'Send SIGTERM (or SIGKILL with -9) to a process by PID.',
          example: 'kill -9 4832',
        },
        {
          command: 'jobs / bg / fg / nohup',
          description: 'Manage background jobs; nohup keeps a process alive after logout.',
          example: 'nohup ./worker.sh &',
        },
        {
          command: 'systemctl status/restart',
          description: 'Inspect or control a systemd-managed service.',
          example: 'systemctl restart nginx',
        },
      ],
    },
    {
      title: 'Permissions',
      entries: [
        {
          command: 'chmod',
          description: 'Change a file\'s permission bits — see the Chmod page for the full octal breakdown.',
          example: 'chmod 644 file.txt',
        },
        {
          command: 'chown',
          description: 'Change a file\'s owning user and/or group.',
          example: 'chown www-data:www-data /var/www/app',
        },
        {
          command: 'sudo -u',
          description: 'Run a command as another user.',
          example: 'sudo -u postgres psql',
        },
      ],
    },
    {
      title: 'Disk & Network Inspection',
      entries: [
        {
          command: 'df -h',
          description: 'Show filesystem disk space usage, human-readable.',
          example: 'df -h',
        },
        {
          command: 'du -sh',
          description: 'Show total size of a directory.',
          example: 'du -sh /var/log/*',
        },
        {
          command: 'ss -tulpn',
          description: 'Show listening TCP/UDP sockets and their owning process.',
          example: 'ss -tulpn',
        },
        {
          command: 'journalctl -u',
          description: 'Show systemd journal logs for one unit (-f to follow).',
          example: 'journalctl -u nginx -f',
        },
      ],
    },
    {
      title: 'Packages',
      entries: [
        {
          command: 'apt update / apt install',
          description: 'Refresh package lists and install a package (Debian/Ubuntu).',
          example: 'apt update && apt install -y curl',
        },
        {
          command: 'dnf install / yum install',
          description: 'Install a package (RHEL/CentOS/Fedora).',
          example: 'dnf install -y curl',
        },
      ],
    },
  ],
}

const iptablesPage: CheatsheetPage = {
  id: 'iptables',
  title: 'iptables Commands',
  description: 'The most-used raw netfilter commands: listing, adding/removing rules, policies, NAT, and persistence.',
  sections: [
    {
      title: 'Listing & Flushing',
      entries: [
        {
          command: 'iptables -L -v -n',
          description: 'List all rules in the filter table with packet counters, numeric (no DNS lookups).',
          example: 'iptables -L -v -n --line-numbers',
        },
        {
          command: 'iptables -t nat -L -v -n',
          description: 'List rules in the nat table specifically.',
          example: 'iptables -t nat -L -v -n',
        },
        {
          command: 'iptables -F',
          description: 'Flush (delete) every rule in a chain, or the whole table if no chain given.',
          example: 'iptables -F INPUT',
        },
        {
          command: 'iptables -Z',
          description: 'Zero the packet/byte counters without touching the rules.',
          example: 'iptables -Z',
        },
      ],
    },
    {
      title: 'Adding & Removing Rules',
      entries: [
        {
          command: 'iptables -A',
          description: 'Append a rule to the end of a chain.',
          example: 'iptables -A INPUT -p tcp --dport 22 -j ACCEPT',
        },
        {
          command: 'iptables -I',
          description: 'Insert a rule at a given position (default: the top, position 1).',
          example: 'iptables -I INPUT 1 -p tcp --dport 443 -j ACCEPT',
        },
        {
          command: 'iptables -D',
          description: 'Delete a rule, either by restating it or by rule number.',
          example: 'iptables -D INPUT 3',
        },
        {
          command: 'iptables -R',
          description: 'Replace the rule at a given position.',
          example: 'iptables -R INPUT 1 -p tcp --dport 80 -j ACCEPT',
        },
      ],
    },
    {
      title: 'Common Matches',
      entries: [
        {
          command: '-s / -d',
          description: 'Match source / destination address or CIDR.',
          example: 'iptables -A INPUT -s 10.0.0.0/8 -j ACCEPT',
        },
        {
          command: '-p tcp --dport',
          description: 'Match a protocol and destination port.',
          example: 'iptables -A INPUT -p tcp --dport 443 -j ACCEPT',
        },
        {
          command: '-m state --state ESTABLISHED,RELATED',
          description: 'Match packets belonging to an already-permitted connection.',
          example: 'iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT',
        },
        {
          command: '-i / -o',
          description: 'Match the incoming / outgoing network interface.',
          example: 'iptables -A INPUT -i eth0 -j ACCEPT',
        },
      ],
    },
    {
      title: 'Policies & NAT',
      entries: [
        {
          command: 'iptables -P',
          description: 'Set a chain\'s default policy for traffic matching no rule.',
          example: 'iptables -P INPUT DROP',
        },
        {
          command: '-j MASQUERADE',
          description: 'Rewrite the source address to the outgoing interface\'s address (typical for a NAT gateway).',
          example: 'iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE',
        },
        {
          command: '-j DNAT --to-destination',
          description: 'Port-forward incoming traffic to an internal host.',
          example: 'iptables -t nat -A PREROUTING -p tcp --dport 8080 -j DNAT --to-destination 10.0.0.5:80',
        },
      ],
    },
    {
      title: 'Persistence',
      entries: [
        {
          command: 'iptables-save',
          description: 'Dump the current ruleset in a restorable text format.',
          example: 'iptables-save > /etc/iptables/rules.v4',
        },
        {
          command: 'iptables-restore',
          description: 'Load a ruleset previously written by iptables-save.',
          example: 'iptables-restore < /etc/iptables/rules.v4',
        },
      ],
    },
  ],
}

const nginxPage: CheatsheetPage = {
  id: 'nginx',
  title: 'nginx',
  description: 'Service management, server blocks, reverse proxying, SSL and logging — the directives from ngx_http_core/ssl/proxy_module used most.',
  sections: [
    {
      title: 'Service Management',
      entries: [
        {
          command: 'nginx -t',
          description: 'Test the configuration syntax without reloading — always run this before reloading in production.',
          example: 'nginx -t\nnginx -t -c /etc/nginx/nginx.conf',
        },
        {
          command: 'systemctl reload nginx',
          description: 'Re-read config and gracefully finish in-flight requests on the old workers — no dropped connections, unlike restart.',
          example: 'systemctl reload nginx',
        },
        {
          command: 'systemctl restart nginx',
          description: 'Stop and start the master process — drops in-flight connections. Prefer reload unless the binary itself changed.',
          example: 'systemctl restart nginx',
        },
        {
          command: 'nginx -s reload',
          description: 'Same graceful reload as systemctl reload, sent directly to the running master process.',
          example: 'nginx -s reload',
        },
        {
          command: 'journalctl -u nginx -f',
          description: 'Follow the nginx service journal — useful when error_log points at syslog rather than a file.',
          example: 'journalctl -u nginx -f',
        },
      ],
    },
    {
      title: 'Server Blocks & Locations',
      entries: [
        {
          command: 'listen',
          description: 'Address/port (or unix socket) the server block accepts connections on. Default *:80.',
          example: 'listen 80;\nlisten 443 ssl;\nlisten [::]:80;',
        },
        {
          command: 'server_name',
          description: 'Virtual host name(s) this block answers for — exact names, wildcards, or a regex.',
          example: 'server_name example.com www.example.com;\nserver_name *.example.com;',
        },
        {
          command: 'root / index',
          description: 'Document root for static files, and the filename(s) tried when a request maps to a directory.',
          example: 'root /var/www/html;\nindex index.html index.htm;',
        },
        {
          command: 'location ^~ / = / ~ /',
          description: 'Location match modifiers, most to least specific: "=" exact match, "^~" prefix (stop regex search), "~"/"~*" case-sensitive/insensitive regex, bare prefix.',
          example: 'location = /favicon.ico { }\nlocation ^~ /static/ { }\nlocation ~* \\.(jpg|png)$ { }',
        },
        {
          command: 'try_files',
          description: 'Tries each path in order and serves the first that exists, falling back to a URI or status code.',
          example: 'location / {\n    try_files $uri $uri/ =404;\n}',
        },
      ],
    },
    {
      title: 'Reverse Proxy',
      entries: [
        {
          command: 'proxy_pass',
          description: 'Forwards the request to an upstream address. A trailing URI on proxy_pass replaces the matched location prefix; without one, the full URI is passed through.',
          example: 'location / {\n    proxy_pass http://127.0.0.1:3000;\n}',
        },
        {
          command: 'proxy_set_header',
          description: 'Nginx does not forward Host or the client IP by default — these four headers are the standard reverse-proxy set.',
          example: 'proxy_set_header Host $host;\nproxy_set_header X-Real-IP $remote_addr;\nproxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\nproxy_set_header X-Forwarded-Proto $scheme;',
        },
        {
          command: 'proxy_http_version',
          description: 'HTTP version nginx speaks to the upstream. Set 1.1 for keepalive connections and WebSocket upgrades.',
          example: 'proxy_http_version 1.1;',
        },
        {
          command: 'proxy_read_timeout',
          description: 'How long nginx waits between successive reads from the upstream before giving up. Default 60s.',
          example: 'proxy_read_timeout 60s;',
        },
      ],
    },
    {
      title: 'SSL/TLS',
      entries: [
        {
          command: 'ssl_certificate / ssl_certificate_key',
          description: 'PEM certificate (chain) and matching private key for this server block.',
          example: 'ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;\nssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;',
        },
        {
          command: 'ssl_protocols',
          description: 'Enabled TLS versions. Current nginx default is TLSv1.2 and TLSv1.3 — do not add SSLv3/TLSv1.0/1.1 back in.',
          example: 'ssl_protocols TLSv1.2 TLSv1.3;',
        },
        {
          command: 'ssl_session_cache / ssl_session_timeout',
          description: 'Shared SSL session cache (across all workers) and how long clients may resume a session without a full handshake.',
          example: 'ssl_session_cache shared:SSL:10m;\nssl_session_timeout 5m;',
        },
      ],
    },
    {
      title: 'Redirects, Logging & Debug',
      entries: [
        {
          command: 'return 301',
          description: 'Issues a permanent redirect — the standard way to force HTTP to HTTPS.',
          example: 'server {\n    listen 80;\n    server_name example.com;\n    return 301 https://$host$request_uri;\n}',
        },
        {
          command: 'access_log / error_log',
          description: 'Per-context log file paths (and, for error_log, a minimum severity level).',
          example: 'access_log /var/log/nginx/access.log;\nerror_log /var/log/nginx/error.log warn;',
        },
        {
          command: 'client_max_body_size',
          description: 'Largest request body nginx accepts before returning 413. Default 1m — the first thing to raise for file uploads.',
          example: 'client_max_body_size 50m;',
        },
      ],
    },
  ],
}

const apachePage: CheatsheetPage = {
  id: 'apache',
  title: 'Apache (httpd)',
  description: 'Service management, VirtualHost basics, access control, reverse proxying and SSL — the mod_core/mod_proxy/mod_ssl directives used most.',
  sections: [
    {
      title: 'Service Management',
      entries: [
        {
          command: 'apachectl configtest',
          description: 'Test the configuration syntax without restarting — always run this before reloading in production.',
          example: 'apachectl configtest\napache2ctl configtest',
        },
        {
          command: 'systemctl reload apache2',
          description: 'Re-read config and gracefully finish in-flight requests — no dropped connections, unlike restart.',
          example: 'systemctl reload apache2\nsystemctl reload httpd',
        },
        {
          command: 'a2ensite / a2dissite',
          description: 'Enable/disable a site config from sites-available by symlinking it into sites-enabled (Debian/Ubuntu layout).',
          example: 'a2ensite example.com.conf\na2dissite 000-default.conf',
        },
        {
          command: 'a2enmod / a2dismod',
          description: 'Enable/disable an Apache module. ssl, rewrite and proxy/proxy_http are the ones most vhosts below actually need.',
          example: 'a2enmod ssl rewrite proxy proxy_http\nsystemctl reload apache2',
        },
        {
          command: 'apache2ctl -M',
          description: 'List every currently loaded module — the fastest way to confirm a directive\'s module is actually enabled.',
          example: 'apache2ctl -M | grep proxy',
        },
      ],
    },
    {
      title: 'VirtualHost & Access Control',
      entries: [
        {
          command: 'ServerName / ServerAlias',
          description: 'Primary hostname this VirtualHost answers for, plus any additional aliases.',
          example: '<VirtualHost *:80>\n    ServerName example.com\n    ServerAlias www.example.com\n</VirtualHost>',
        },
        {
          command: 'DocumentRoot',
          description: 'Directory Apache serves files from for this VirtualHost. Default /usr/local/apache/htdocs (distro packages usually override it).',
          example: 'DocumentRoot /var/www/example.com/htdocs',
        },
        {
          command: '<Directory> / AllowOverride',
          description: 'Scopes directives to a filesystem path. AllowOverride controls which .htaccess directives that path honors — default is None.',
          example: '<Directory /var/www/example.com/htdocs>\n    AllowOverride None\n    Require all granted\n</Directory>',
        },
        {
          command: 'Require all granted / denied',
          description: 'mod_authz_core access control — the modern replacement for the old Order/Allow/Deny syntax.',
          example: 'Require all granted\nRequire ip 10.0.0.0/8',
        },
      ],
    },
    {
      title: 'Reverse Proxy',
      entries: [
        {
          command: 'ProxyPass / ProxyPassReverse',
          description: 'Forwards matching requests to a backend and rewrites Location/Content-Location headers in responses back to the public path.',
          example: 'ProxyPass / http://127.0.0.1:3000/\nProxyPassReverse / http://127.0.0.1:3000/',
        },
        {
          command: 'ProxyPreserveHost On',
          description: 'Forwards the original Host header to the backend instead of the backend\'s own hostname — needed by most apps that generate absolute URLs.',
          example: 'ProxyPreserveHost On',
        },
        {
          command: 'ProxyRequests Off',
          description: 'Disables forward-proxy mode. Always set this alongside ProxyPass — without it a misconfigured vhost can become an open proxy.',
          example: 'ProxyRequests Off',
        },
      ],
    },
    {
      title: 'SSL/TLS & Redirects',
      entries: [
        {
          command: 'SSLEngine on',
          description: 'Enables mod_ssl for this VirtualHost. Requires the ssl module enabled (a2enmod ssl).',
          example: 'SSLEngine on',
        },
        {
          command: 'SSLCertificateFile / SSLCertificateKeyFile',
          description: 'Certificate (chain) and matching private key for this VirtualHost.',
          example: 'SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem\nSSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem',
        },
        {
          command: 'Redirect permanent',
          description: 'Simple unconditional redirect — the lightest-weight way to force HTTP to HTTPS for a whole vhost.',
          example: '<VirtualHost *:80>\n    ServerName example.com\n    Redirect permanent / https://example.com/\n</VirtualHost>',
        },
        {
          command: 'RewriteEngine / RewriteRule',
          description: 'mod_rewrite conditional URL rewriting — reach for this only when a plain Redirect can\'t express the logic.',
          example: 'RewriteEngine On\nRewriteCond %{HTTPS} off\nRewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]',
        },
      ],
    },
    {
      title: 'Logging',
      entries: [
        {
          command: 'ErrorLog / LogLevel',
          description: 'Per-vhost error log path, plus the minimum severity written to it.',
          example: 'ErrorLog /var/log/apache2/example.com-error.log\nLogLevel warn',
        },
        {
          command: 'CustomLog',
          description: 'Access log path and format name (combined includes referrer + user-agent; common omits them).',
          example: 'CustomLog /var/log/apache2/example.com-access.log combined',
        },
      ],
    },
  ],
}

export const CHEATSHEET_PAGES: CheatsheetPage[] = [
  gitPage,
  regexPage,
  sysctlPage,
  crontabPage,
  chmodPage,
  httpStatusPage,
  commonPortsPage,
  dockerPage,
  terraformPage,
  ansiblePage,
  kubernetesPage,
  powershellPage,
  windowsCmdPage,
  linuxCommandsPage,
  iptablesPage,
  nginxPage,
  apachePage,
]

export const EXTERNAL_RESOURCE_LINKS: ReferenceLink[] = [
  {
    name: 'Zabbix',
    url: 'https://www.zabbix.com/documentation/current/',
    description: 'Official Zabbix documentation: monitoring architecture, templates, and configuration reference.',
    type: 'documentation',
    tags: [
      'zabbix',
      'monitoring',
    ],
  },
  {
    name: 'Ceph',
    url: 'https://docs.ceph.com/en/latest/',
    description: 'Official Ceph documentation: cluster architecture, RADOS, CRUSH maps, and deployment guides.',
    type: 'documentation',
    tags: [
      'ceph',
      'storage',
    ],
  },
  {
    name: 'PostgreSQL',
    url: 'https://www.postgresql.org/docs/',
    description: 'Official PostgreSQL manual: SQL reference, server configuration, and administration.',
    type: 'documentation',
    tags: [
      'postgresql',
      'database',
    ],
  },
  {
    name: 'Kubernetes',
    url: 'https://kubernetes.io/docs/home/',
    description: 'Official Kubernetes documentation: concepts, workloads, networking, and cluster administration.',
    type: 'documentation',
    tags: [
      'kubernetes',
      'containers',
    ],
  },
  {
    name: 'Linux Kernel',
    url: 'https://www.kernel.org/doc/html/latest/',
    description: 'Official Linux kernel documentation: subsystems, admin-guide, and sysctl/proc filesystem references.',
    type: 'documentation',
    tags: [
      'linux',
      'kernel',
    ],
  },
  {
    name: 'Network segmentation cheat sheet',
    url: 'https://github.com/sergiomarotco/Network-segmentation-cheat-sheet',
    description: 'Reference guide for designing secure network segmentation across zones and trust boundaries.',
    type: 'documentation',
    tags: [
      'networking',
      'security',
      'cheatsheet',
    ],
  },
  {
    name: 'SRE Checklist',
    url: 'https://github.com/bregman-arie/sre-checklist',
    description: 'A checklist of practices and questions for evaluating and running reliable production services.',
    type: 'documentation',
    tags: [
      'sre',
      'checklist',
    ],
  },
  {
    name: 'System Design (karanpratapsingh)',
    url: 'https://github.com/karanpratapsingh/system-design',
    description: 'Written explanations of core system design concepts, patterns, and building blocks.',
    type: 'documentation',
    tags: [
      'system-design',
    ],
  },
  {
    name: 'System Design Notebook',
    url: 'https://github.com/bregman-arie/system-design-notebook',
    description: 'Notes and write-ups covering system design fundamentals, trade-offs, and interview topics.',
    type: 'documentation',
    tags: [
      'system-design',
    ],
  },
  {
    name: 'Full Stack FastAPI Template',
    url: 'https://github.com/fastapi/full-stack-fastapi-template',
    description: 'Official FastAPI full-stack project template documenting a production-ready backend/frontend setup.',
    type: 'documentation',
    tags: [
      'fastapi',
      'python',
      'template',
    ],
  },
  {
    name: 'System Design 101',
    url: 'https://github.com/ByteByteGoHq/system-design-101',
    description: 'Visual, diagram-heavy explanations of system design concepts — a curated visual reference, not docs.',
    type: 'curatedList',
    tags: [
      'system-design',
      'visual',
    ],
  },
  {
    name: 'Awesome System Design Resources',
    url: 'https://github.com/ashishps1/awesome-system-design-resources',
    description: 'A curated collection of system design articles, videos, and case studies.',
    type: 'curatedList',
    tags: [
      'system-design',
    ],
  },
  {
    name: 'Awesome Scalability',
    url: 'https://github.com/binhnguyennus/awesome-scalability',
    description: 'A curated list of patterns and articles for building scalable, reliable, and performant systems.',
    type: 'curatedList',
    tags: [
      'system-design',
      'scalability',
      'distributed-systems',
    ],
  },
  {
    name: 'Awesome Design Patterns',
    url: 'https://github.com/DovAmir/awesome-design-patterns',
    description: 'A curated list of software and architecture design pattern resources.',
    type: 'curatedList',
    tags: [
      'software-design',
      'patterns',
    ],
  },
  {
    name: 'Awesome Docker',
    url: 'https://github.com/veggiemonk/awesome-docker',
    description: 'A curated list of Docker resources: tools, tutorials, and projects.',
    type: 'curatedList',
    tags: [
      'docker',
    ],
  },
  {
    name: 'Awesome Compose',
    url: 'https://github.com/docker/awesome-compose',
    description: 'Curated, ready-to-use Docker Compose sample application definitions.',
    type: 'curatedList',
    tags: [
      'docker',
      'compose',
    ],
  },
  {
    name: 'System Design Primer',
    url: 'https://github.com/donnemartin/system-design-primer',
    description: 'A large, widely-referenced curated collection of system design articles and resources.',
    type: 'curatedList',
    tags: [
      'system-design',
    ],
  },
  {
    name: 'Awesome OpenTofu',
    url: 'https://github.com/virtualroot/awesome-opentofu',
    description: 'A curated list of OpenTofu/Terraform providers, modules, and infrastructure-as-code tooling.',
    type: 'curatedList',
    tags: [
      'iac',
      'opentofu',
      'terraform',
    ],
  },
  {
    name: 'Awesome Cheatsheets',
    url: 'https://github.com/LeCoupa/awesome-cheatsheets',
    description: 'A curated collection of cheatsheets for languages, frameworks, and tools.',
    type: 'curatedList',
    tags: [
      'cheatsheets',
      'programming',
    ],
  },
  {
    name: 'How They DevOps',
    url: 'https://github.com/bregman-arie/howtheydevops',
    description: 'A curated collection of engineering blog posts on how real companies do DevOps.',
    type: 'curatedList',
    tags: [
      'devops',
      'case-studies',
    ],
  },
  {
    name: 'How They SRE',
    url: 'https://github.com/upgundecha/howtheysre',
    description: 'A curated collection of engineering blog posts on how real companies practice SRE.',
    type: 'curatedList',
    tags: [
      'sre',
      'case-studies',
    ],
  },
  {
    name: 'Free for Dev',
    url: 'https://github.com/ripienaar/free-for-dev',
    description: 'A curated list of SaaS/PaaS/IaaS offerings with a free tier for developers and ops.',
    type: 'curatedList',
    tags: [
      'tools',
      'free-tier',
    ],
  },
  {
    name: 'Awesome SRE',
    url: 'https://github.com/dastergon/awesome-sre',
    description: 'A curated list of Site Reliability Engineering resources: articles, talks, and tools.',
    type: 'curatedList',
    tags: [
      'sre',
    ],
  },
  {
    name: 'Awesome CursorRules',
    url: 'https://github.com/PatrickJS/awesome-cursorrules',
    description: 'A curated list of .cursorrules configurations for AI-assisted coding tools.',
    type: 'curatedList',
    tags: [
      'ai',
      'tooling',
    ],
  },
  {
    name: 'DevOps Resources',
    url: 'https://github.com/bregman-arie/devops-resources',
    description: 'A curated collection of DevOps resources: tools, guides, and learning material.',
    type: 'curatedList',
    tags: [
      'devops',
    ],
  },
  {
    name: 'Awesome Privacy',
    url: 'https://github.com/pluja/awesome-privacy',
    description: 'A curated list of privacy-respecting services, tools, and software.',
    type: 'curatedList',
    tags: [
      'privacy',
      'security',
    ],
  },
  {
    name: 'Awesome Prometheus',
    url: 'https://github.com/roaldnefs/awesome-prometheus',
    description: 'A curated list of Prometheus exporters, tools, and resources.',
    type: 'curatedList',
    tags: [
      'monitoring',
      'prometheus',
    ],
  },
  {
    name: 'Awesome DevSecOps',
    url: 'https://github.com/devsecops/awesome-devsecops',
    description: 'A curated list of DevSecOps tools, practices, and resources.',
    type: 'curatedList',
    tags: [
      'devsecops',
      'security',
    ],
  },
  {
    name: 'Awesome Sysadmin',
    url: 'https://github.com/awesome-foss/awesome-sysadmin',
    description: 'A curated list of open-source sysadmin software and resources.',
    type: 'curatedList',
    tags: [
      'sysadmin',
      'foss',
    ],
  },
  {
    name: 'DevOps Exercises',
    url: 'https://github.com/bregman-arie/devops-exercises',
    description: 'Hands-on DevOps/SRE/Linux/networking exercises and interview questions.',
    type: 'exercise',
    tags: [
      'devops',
      'interview-prep',
    ],
  },
  {
    name: 'ProjectLearn — Project Based Learning',
    url: 'https://github.com/Xtremilicious/projectlearn-project-based-learning',
    description: 'A curated collection of tutorials for learning by building real projects.',
    type: 'exercise',
    tags: [
      'learning',
      'projects',
    ],
  },
  {
    name: 'Test Your Sysadmin Skills',
    url: 'https://github.com/trimstray/test-your-sysadmin-skills',
    description: 'Practical Linux/sysadmin challenges to test and sharpen troubleshooting skills.',
    type: 'exercise',
    tags: [
      'sysadmin',
      'linux',
    ],
  },
  {
    name: 'DevOps Roadmap',
    url: 'https://github.com/milanm/DevOps-Roadmap',
    description: 'A structured roadmap of skills and technologies to learn for a DevOps career path.',
    type: 'roadmap',
    tags: [
      'devops',
    ],
  },
  {
    name: 'Infraverse',
    url: 'https://github.com/bregman-arie/infraverse',
    description: 'A map of the infrastructure/DevOps universe: tools, categories, and how they relate.',
    type: 'roadmap',
    tags: [
      'infrastructure',
      'devops',
    ],
  },
]
