import 'dart:math' as math;

import '../ports/i_tool_use_case.dart';

/// Backing database engine. Only affects the on-disk overhead multiplier
/// applied to the raw history/trends estimate — see [ZabbixSizer].
enum ZabbixDbEngine {
  postgresql('PostgreSQL'),
  mysql('MySQL / MariaDB');

  const ZabbixDbEngine(this.label);

  final String label;
}

/// Inputs for the Zabbix capacity/sizing estimate.
class ZabbixSizerInput {
  const ZabbixSizerInput({
    required this.hostCount,
    required this.itemsPerHost,
    required this.checkIntervalSeconds,
    required this.historyRetentionDays,
    required this.trendsRetentionDays,
    this.dbEngine = ZabbixDbEngine.postgresql,
    this.cpuCores = 8,
  });

  /// Number of monitored hosts.
  final int hostCount;

  /// Average number of enabled items per host.
  final int itemsPerHost;

  /// Average item check interval, in seconds. This is the "refresh rate"
  /// term in Zabbix's own disk-space formula.
  final double checkIntervalSeconds;

  /// `Housekeeping -> History storage period`, in days.
  final int historyRetentionDays;

  /// `Housekeeping -> Trend storage period`, in days.
  final int trendsRetentionDays;

  final ZabbixDbEngine dbEngine;

  /// CPU cores on the Zabbix server host. Zabbix documents that
  /// `StartPreprocessors` "should be set to no less than the available CPU
  /// core count", so the recommendation is floored at this value.
  final int cpuCores;
}

/// Recommended `zabbix_server.conf` worker/cache values plus the storage
/// estimate they were derived from.
class ZabbixSizerResult {
  const ZabbixSizerResult({
    required this.totalItems,
    required this.nvps,
    required this.startPollers,
    required this.startPollersUnreachable,
    required this.startPreprocessors,
    required this.startTrappers,
    required this.startDbSyncers,
    required this.cacheSizeMb,
    required this.historyCacheSizeMb,
    required this.historyIndexCacheSizeMb,
    required this.trendCacheSizeMb,
    required this.valueCacheSizeMb,
    required this.historyValuesPerDay,
    required this.historyBytesPerDay,
    required this.historyBytesTotal,
    required this.trendRowsPerDay,
    required this.trendsBytesPerDay,
    required this.trendsBytesTotal,
    required this.engineOverheadFactor,
    required this.totalDbBytes,
    required this.dbEngine,
  });

  /// `hostCount * itemsPerHost`.
  final int totalItems;

  /// **New Values Per Second** — Zabbix's central capacity metric.
  /// `totalItems / checkIntervalSeconds`.
  final double nvps;

  final int startPollers;
  final int startPollersUnreachable;
  final int startPreprocessors;
  final int startTrappers;
  final int startDbSyncers;

  final int cacheSizeMb;
  final int historyCacheSizeMb;
  final int historyIndexCacheSizeMb;
  final int trendCacheSizeMb;
  final int valueCacheSizeMb;

  /// `nvps * 86400`.
  final double historyValuesPerDay;
  final double historyBytesPerDay;

  /// History growth across the whole retention window.
  final double historyBytesTotal;

  /// One trend row per item per hour: `totalItems * 24`.
  final double trendRowsPerDay;
  final double trendsBytesPerDay;
  final double trendsBytesTotal;

  /// Index/page overhead multiplier applied on top of the raw row bytes.
  final double engineOverheadFactor;

  /// `(history + trends) * engineOverheadFactor + configuration`.
  final double totalDbBytes;

  final ZabbixDbEngine dbEngine;

  /// Ready-to-paste `zabbix_server.conf` snippet.
  String get configText {
    final nvpsText = nvps.toStringAsFixed(2);
    return '''
### Generated by InfraKit Studio - Zabbix Monitoring Sizing
### Estimated load: $nvpsText NVPS ($totalItems items / ${_trimZeros(_intervalSeconds)}s interval)
### Engine: ${dbEngine.label} | history ${_plural(historyValuesPerDay)}/day

StartPollers=$startPollers
StartPollersUnreachable=$startPollersUnreachable
StartPreprocessors=$startPreprocessors
StartTrappers=$startTrappers
StartDBSyncers=$startDbSyncers

CacheSize=${cacheSizeMb}M
HistoryCacheSize=${historyCacheSizeMb}M
HistoryIndexCacheSize=${historyIndexCacheSizeMb}M
TrendCacheSize=${trendCacheSizeMb}M
ValueCacheSize=${valueCacheSizeMb}M''';
  }

  double get _intervalSeconds => totalItems / nvps;

  static String _trimZeros(double value) {
    final text = value.toStringAsFixed(2);
    return text.endsWith('.00') ? text.substring(0, text.length - 3) : text;
  }

  static String _plural(double values) => '${values.round()} values';
}

/// Formats a byte count as B / KB / MB / GB / TB with two decimals.
/// Uses binary (1024) steps, matching how `df`/`free` report disk usage.
String formatZabbixBytes(double bytes) {
  if (bytes < 1024) return '${bytes.round()} B';
  const units = ['KB', 'MB', 'GB', 'TB', 'PB'];
  var value = bytes / 1024;
  var unit = 0;
  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024;
    unit++;
  }
  return '${value.toStringAsFixed(2)} ${units[unit]}';
}

/// Zabbix monitoring capacity and database-growth sizer.
///
/// Pure math, zero I/O, zero Flutter.
///
/// ## Documented constants (Zabbix official documentation)
///
/// Sources — Zabbix manual, *Installation -> Requirements -> Database size*
/// (<https://www.zabbix.com/documentation/current/en/manual/installation/requirements>)
/// and *Appendix -> Configuration -> Zabbix server*
/// (<https://www.zabbix.com/documentation/current/en/manual/appendix/config/zabbix_server>):
///
/// * History disk space: `days * (items / refresh rate) * 24 * 3600 * bytes`.
/// * Trends disk space: `days * (items / 3600) * 24 * 3600 * bytes` — the
///   `3600` is the one-hour trend averaging period, i.e. one trend row per
///   item per hour.
/// * [historyBytesPerValue] = 90 — "around 90 bytes per value" for numeric
///   items. The docs note the real figure varies from ~40 bytes to hundreds
///   depending on engine and value type (text/log items are ~500 bytes), so
///   this is the documented *numeric* midpoint, not a hard number.
/// * [trendsBytesPerRow] = 90 — the docs quote ~90 bytes for each hourly
///   min/max/avg/count set.
/// * [historyIndexBytesPerItem] = 100 — "the index cache size needs roughly
///   100 bytes to cache one item" (HistoryIndexCacheSize).
/// * [configurationBytes] = 10 MB — "Fixed size. Normally 10MB or less."
/// * `StartDBSyncers` default is 4 and "the default value should be enough
///   to handle up to 4000 NVPS", which is where [nvpsPerDbSyncer] = 1000
///   comes from (4000 NVPS / 4 syncers).
/// * Documented defaults used as *floors* so a recommendation never comes
///   out below stock Zabbix: CacheSize 32M, HistoryCacheSize 16M,
///   HistoryIndexCacheSize 4M, ValueCacheSize 8M, TrendCacheSize 4M,
///   StartPollers 5, StartPreprocessors 16, StartTrappers 5,
///   StartPollersUnreachable 1.
/// * Documented maxima used as caps: HistoryCacheSize / HistoryIndexCacheSize
///   / TrendCacheSize 2G; CacheSize / ValueCacheSize 64G; poller-style
///   parameters 1000; StartDBSyncers 100. `StartPreprocessors` "should be
///   set to no less than the available CPU core count".
///
/// ## Rule-of-thumb figures (NOT from Zabbix documentation)
///
/// Zabbix publishes defaults and maxima but does not publish a formula that
/// maps NVPS to cache sizes or poller counts — real numbers depend on check
/// type, preprocessing, trigger complexity and DB latency. The following are
/// therefore **heuristic starting points**, expressed as "scale the stock
/// default linearly with load", and should be verified against the internal
/// items Zabbix provides (`zabbix[wcache,...]`, `zabbix[vcache,buffer,pfree]`,
/// `zabbix[process,poller,avg,busy]`) once the server is running:
///
/// * [nvpsPerPoller] = 100 — one extra poller per 100 NVPS.
/// * [nvpsPerTrapper] = 500.
/// * [nvpsPerPreprocessor] = 250.
/// * [itemsPerCacheSizeUnit] = 10000 — one stock 32M CacheSize unit per
///   10k items of configuration.
/// * [nvpsPerHistoryCacheUnit] = 1000 — one stock 16M HistoryCacheSize unit
///   per 1000 NVPS.
/// * [itemsPerValueCacheUnit] = 1000 — one stock 8M ValueCacheSize unit per
///   1000 items.
/// * [itemsPerTrendCacheUnit] = 1000 — one stock 4M TrendCacheSize unit per
///   1000 items.
/// * Unreachable pollers = 1 per 10 regular pollers.
/// * Engine overhead: PostgreSQL 1.30x, MySQL/InnoDB 1.20x on top of the raw
///   row bytes, covering primary-key and secondary-index storage plus page
///   fill factor. A rough industry figure, not a Zabbix-published one — and
///   it does not model TimescaleDB or partition compression, which typically
///   cut real usage well below this.
class ZabbixSizer implements IToolUseCase<ZabbixSizerInput, ZabbixSizerResult> {
  const ZabbixSizer();

  // ---- documented constants ----
  static const int historyBytesPerValue = 90;
  static const int trendsBytesPerRow = 90;
  static const int historyIndexBytesPerItem = 100;
  static const double configurationBytes = 10 * 1024 * 1024;
  static const int secondsPerDay = 86400;
  static const int trendRowsPerItemPerDay = 24;
  static const double nvpsPerDbSyncer = 1000;

  // Documented stock defaults, used as floors.
  static const int defaultCacheSizeMb = 32;
  static const int defaultHistoryCacheSizeMb = 16;
  static const int defaultHistoryIndexCacheSizeMb = 4;
  static const int defaultTrendCacheSizeMb = 4;
  static const int defaultValueCacheSizeMb = 8;
  static const int defaultStartPollers = 5;
  static const int defaultStartPreprocessors = 16;
  static const int defaultStartTrappers = 5;

  // Documented maxima, used as caps.
  static const int maxSmallCacheMb = 2 * 1024; // 2G
  static const int maxLargeCacheMb = 64 * 1024; // 64G
  static const int maxWorkers = 1000;
  static const int maxDbSyncers = 100;

  // ---- rule-of-thumb scaling factors (see class doc) ----
  static const double nvpsPerPoller = 100;
  static const double nvpsPerTrapper = 500;
  static const double nvpsPerPreprocessor = 250;
  static const double itemsPerCacheSizeUnit = 10000;
  static const double nvpsPerHistoryCacheUnit = 1000;
  static const double itemsPerValueCacheUnit = 1000;
  static const double itemsPerTrendCacheUnit = 1000;

  @override
  ZabbixSizerResult execute(ZabbixSizerInput input) {
    if (input.hostCount <= 0) {
      throw ArgumentError('hostCount must be positive');
    }
    if (input.itemsPerHost <= 0) {
      throw ArgumentError('itemsPerHost must be positive');
    }
    if (!(input.checkIntervalSeconds > 0) || !input.checkIntervalSeconds.isFinite) {
      throw ArgumentError('checkIntervalSeconds must be greater than zero');
    }
    if (input.historyRetentionDays <= 0) {
      throw ArgumentError('historyRetentionDays must be positive');
    }
    if (input.trendsRetentionDays <= 0) {
      throw ArgumentError('trendsRetentionDays must be positive');
    }
    if (input.cpuCores <= 0) {
      throw ArgumentError('cpuCores must be positive');
    }

    final totalItems = input.hostCount * input.itemsPerHost;
    final nvps = totalItems / input.checkIntervalSeconds;

    // ---- storage (documented Zabbix formulas) ----
    final historyValuesPerDay = nvps * secondsPerDay;
    final historyBytesPerDay = historyValuesPerDay * historyBytesPerValue;
    final historyBytesTotal = historyBytesPerDay * input.historyRetentionDays;

    final trendRowsPerDay = totalItems * trendRowsPerItemPerDay.toDouble();
    final trendsBytesPerDay = trendRowsPerDay * trendsBytesPerRow;
    final trendsBytesTotal = trendsBytesPerDay * input.trendsRetentionDays;

    final overhead = switch (input.dbEngine) {
      ZabbixDbEngine.postgresql => 1.30,
      ZabbixDbEngine.mysql => 1.20,
    };
    final totalDbBytes =
        (historyBytesTotal + trendsBytesTotal) * overhead + configurationBytes;

    // ---- workers ----
    final startPollers = _clampInt(
      (nvps / nvpsPerPoller).ceil(),
      defaultStartPollers,
      maxWorkers,
    );
    final startPollersUnreachable = _clampInt(startPollers ~/ 10, 1, maxWorkers);
    final startPreprocessors = _clampInt(
      math.max((nvps / nvpsPerPreprocessor).ceil(), input.cpuCores),
      defaultStartPreprocessors,
      maxWorkers,
    );
    final startTrappers = _clampInt(
      (nvps / nvpsPerTrapper).ceil(),
      defaultStartTrappers,
      maxWorkers,
    );
    // Zabbix documents that the stock 4 syncers cover up to 4000 NVPS.
    final startDbSyncers = _clampInt(
      (nvps / nvpsPerDbSyncer).ceil(),
      4,
      maxDbSyncers,
    );

    // ---- caches ----
    final cacheSizeMb = _clampInt(
      (totalItems / itemsPerCacheSizeUnit).ceil() * defaultCacheSizeMb,
      defaultCacheSizeMb,
      maxLargeCacheMb,
    );
    final historyCacheSizeMb = _clampInt(
      (nvps / nvpsPerHistoryCacheUnit).ceil() * defaultHistoryCacheSizeMb,
      defaultHistoryCacheSizeMb,
      maxSmallCacheMb,
    );
    // The only cache with a documented per-item cost: ~100 bytes per item.
    final historyIndexCacheSizeMb = _clampInt(
      (totalItems * historyIndexBytesPerItem / (1024 * 1024)).ceil(),
      defaultHistoryIndexCacheSizeMb,
      maxSmallCacheMb,
    );
    final trendCacheSizeMb = _clampInt(
      (totalItems / itemsPerTrendCacheUnit).ceil() * defaultTrendCacheSizeMb,
      defaultTrendCacheSizeMb,
      maxSmallCacheMb,
    );
    final valueCacheSizeMb = _clampInt(
      (totalItems / itemsPerValueCacheUnit).ceil() * defaultValueCacheSizeMb,
      defaultValueCacheSizeMb,
      maxLargeCacheMb,
    );

    return ZabbixSizerResult(
      totalItems: totalItems,
      nvps: nvps,
      startPollers: startPollers,
      startPollersUnreachable: startPollersUnreachable,
      startPreprocessors: startPreprocessors,
      startTrappers: startTrappers,
      startDbSyncers: startDbSyncers,
      cacheSizeMb: cacheSizeMb,
      historyCacheSizeMb: historyCacheSizeMb,
      historyIndexCacheSizeMb: historyIndexCacheSizeMb,
      trendCacheSizeMb: trendCacheSizeMb,
      valueCacheSizeMb: valueCacheSizeMb,
      historyValuesPerDay: historyValuesPerDay,
      historyBytesPerDay: historyBytesPerDay,
      historyBytesTotal: historyBytesTotal,
      trendRowsPerDay: trendRowsPerDay,
      trendsBytesPerDay: trendsBytesPerDay,
      trendsBytesTotal: trendsBytesTotal,
      engineOverheadFactor: overhead,
      totalDbBytes: totalDbBytes,
      dbEngine: input.dbEngine,
    );
  }

  int _clampInt(int value, int min, int max) =>
      value < min ? min : (value > max ? max : value);
}
