import { useMemo, useRef, useState } from 'react'
import { Copy, Eye, EyeOff, Plus, Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Slider } from '@/components/ui/slider'
import { Switch } from '@/components/ui/switch'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { ToolDetailScaffold } from '@/adapters/ui/shell/ToolDetailScaffold'
import {
  BasicAuthHeaderBuilder,
  HTPASSWD_ALGORITHM_INFO,
  HTPASSWD_DEFAULT_BCRYPT_COST,
  HTPASSWD_MAX_BCRYPT_COST,
  HTPASSWD_MIN_BCRYPT_COST,
  HTPASSWD_WEAK_BCRYPT_COST,
  HtpasswdGenerator,
  basicAuthHeaderLine,
  htpasswdAlgorithmHasCostFactor,
  validateHtpasswdUsername,
  type HtpasswdAlgorithm,
  type HtpasswdGeneratorResult,
} from '@/core/utility/htpasswdGenerator'

const generator = new HtpasswdGenerator()
const headerBuilder = new BasicAuthHeaderBuilder()

const ALL_ALGORITHMS: HtpasswdAlgorithm[] = ['bcrypt', 'apr1', 'sha1']

interface CredentialRow {
  id: number
  username: string
  password: string
  obscure: boolean
}

function newRow(id: number): CredentialRow {
  return { id, username: '', password: '', obscure: true }
}

export function HtpasswdGeneratorScreen() {
  const [algorithm, setAlgorithm] = useState<HtpasswdAlgorithm>('bcrypt')
  const [bcryptCost, setBcryptCost] = useState(HTPASSWD_DEFAULT_BCRYPT_COST)
  const [includeHeaderComment, setIncludeHeaderComment] = useState(false)
  const nextId = useRef(1)
  const [rows, setRows] = useState<CredentialRow[]>([newRow(0)])

  function addRow() {
    setRows((prev) => [...prev, newRow(nextId.current++)])
  }

  function removeRow(id: number) {
    setRows((prev) => prev.filter((r) => r.id !== id))
  }

  function updateRow(id: number, patch: Partial<CredentialRow>) {
    setRows((prev) => prev.map((r) => (r.id === id ? { ...r, ...patch } : r)))
  }

  const result = useMemo(() => {
    try {
      const value: HtpasswdGeneratorResult = generator.execute({
        entries: rows.map((r) => ({ username: r.username, password: r.password })),
        algorithm,
        bcryptCost,
        includeHeaderComment,
      })
      return { value, error: null }
    } catch (e) {
      return { value: null, error: e instanceof Error ? e.message : String(e) }
    }
  }, [rows, algorithm, bcryptCost, includeHeaderComment])

  const algorithmInfo = HTPASSWD_ALGORITHM_INFO[algorithm]

  return (
    <ToolDetailScaffold
      title="htpasswd / Basic Auth Generator"
      copyText={result.value?.fileContent}
      inputPanel={
        <div className="flex max-w-xl flex-col gap-5">
          <div className="flex flex-col gap-1.5">
            <Label>Algorithm</Label>
            <Select value={algorithm} onValueChange={(v) => setAlgorithm((v as HtpasswdAlgorithm) ?? algorithm)}>
              <SelectTrigger className="w-full">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {ALL_ALGORITHMS.map((a) => (
                  <SelectItem key={a} value={a}>
                    {HTPASSWD_ALGORITHM_INFO[a].label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <p className="text-xs text-muted-foreground">{algorithmInfo.description}</p>
            {algorithmInfo.isLegacy ? (
              <p className="text-xs text-destructive">Legacy format — do not choose this for a new deployment.</p>
            ) : null}
          </div>

          {htpasswdAlgorithmHasCostFactor(algorithm) ? (
            <div className="flex flex-col gap-2">
              <Label>bcrypt cost: {bcryptCost}</Label>
              <Slider
                value={bcryptCost}
                min={HTPASSWD_MIN_BCRYPT_COST}
                max={HTPASSWD_MAX_BCRYPT_COST}
                step={1}
                onValueChange={(v) => setBcryptCost(v as number)}
              />
              {bcryptCost < HTPASSWD_WEAK_BCRYPT_COST ? (
                <p className="text-xs text-destructive">
                  Cost {bcryptCost} is low — {HTPASSWD_WEAK_BCRYPT_COST} is the minimum worth deploying.
                </p>
              ) : null}
            </div>
          ) : null}

          <label className="flex items-center justify-between gap-3 text-sm">
            <span>Include a &quot;# generated by&quot; header comment</span>
            <Switch checked={includeHeaderComment} onCheckedChange={setIncludeHeaderComment} />
          </label>

          <div>
            <div className="mb-2 flex items-center justify-between">
              <p className="text-sm font-medium">Users</p>
              <Button type="button" size="sm" variant="ghost" onClick={addRow}>
                <Plus className="size-4" /> Add user
              </Button>
            </div>
            <div className="flex flex-col gap-3">
              {rows.map((row) => (
                <CredentialRowView
                  key={row.id}
                  row={row}
                  onChange={(patch) => updateRow(row.id, patch)}
                  onRemove={() => removeRow(row.id)}
                />
              ))}
            </div>
          </div>
        </div>
      }
      outputPanel={
        <div className="flex flex-col gap-5">
          <div>
            <p className="mb-2 text-sm font-medium">Generated .htpasswd file</p>
            {result.error ? (
              <p className="text-sm text-destructive">{result.error}</p>
            ) : (
              <>
                {result.value && result.value.warnings.length > 0 ? (
                  <Alert className="mb-3">
                    <AlertTitle>Advisories</AlertTitle>
                    <AlertDescription>
                      {result.value.warnings.map((w) => (
                        <p key={w}>{w}</p>
                      ))}
                    </AlertDescription>
                  </Alert>
                ) : null}
                <pre className="max-w-full overflow-x-auto whitespace-pre rounded-lg border border-border/60 bg-background p-3 font-mono text-xs">
                  {result.value?.fileContent}
                </pre>
              </>
            )}
          </div>

          <div>
            <p className="text-sm font-medium">Basic auth header</p>
            <p className="mb-2 text-xs text-muted-foreground">
              Authorization header for each user above — paste straight into a request.
            </p>
            <div className="flex flex-col gap-2">
              {rows.map((row) => (
                <HeaderRow key={row.id} username={row.username} password={row.password} />
              ))}
            </div>
          </div>
        </div>
      }
    />
  )
}

function CredentialRowView({
  row,
  onChange,
  onRemove,
}: {
  row: CredentialRow
  onChange: (patch: Partial<CredentialRow>) => void
  onRemove: () => void
}) {
  const usernameError = row.username.length === 0 ? null : validateHtpasswdUsername(row.username)

  return (
    <div className="rounded-lg border border-border/60 bg-muted/20 p-3">
      <div className="flex flex-wrap items-start gap-3">
        <div className="flex flex-1 flex-col gap-1.5">
          <Label>Username</Label>
          <Input value={row.username} onChange={(e) => onChange({ username: e.target.value })} />
          {usernameError ? <p className="text-xs text-destructive">{usernameError}</p> : null}
        </div>
        <div className="flex flex-1 flex-col gap-1.5">
          <Label>Password</Label>
          <div className="relative">
            <Input
              type={row.obscure ? 'password' : 'text'}
              value={row.password}
              onChange={(e) => onChange({ password: e.target.value })}
              className="pr-9"
            />
            <button
              type="button"
              className="absolute inset-y-0 right-2 flex items-center text-muted-foreground"
              onClick={() => onChange({ obscure: !row.obscure })}
            >
              {row.obscure ? <Eye className="size-4" /> : <EyeOff className="size-4" />}
            </button>
          </div>
        </div>
        <Button type="button" size="icon-sm" variant="ghost" className="mt-6" onClick={onRemove}>
          <Trash2 className="size-4" />
        </Button>
      </div>
    </div>
  )
}

function HeaderRow({ username, password }: { username: string; password: string }) {
  const [copied, setCopied] = useState(false)

  const header = useMemo(() => {
    try {
      return basicAuthHeaderLine(headerBuilder.execute({ username, password }))
    } catch {
      return null
    }
  }, [username, password])

  async function handleCopy() {
    if (!header) return
    await navigator.clipboard.writeText(header)
    setCopied(true)
    setTimeout(() => setCopied(false), 1000)
  }

  return (
    <div className="flex items-center gap-2">
      <div className="flex-1 rounded-md border border-border/60 bg-background px-3 py-2">
        {header ? (
          <p className="break-all font-mono text-xs">{header}</p>
        ) : (
          <p className="text-xs text-muted-foreground">
            {username.length === 0 ? 'Add a username to generate this header.' : 'Cannot build a header for this username.'}
          </p>
        )}
      </div>
      <Button variant="ghost" size="icon-sm" disabled={!header} onClick={handleCopy}>
        <Copy className="size-3.5" />
        <span className="sr-only">{copied ? 'Copied' : 'Copy header'}</span>
      </Button>
    </div>
  )
}
