import { useCallback, useEffect, useRef, useState } from 'react'
import { Copy, KeyRound, Loader2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { ToolDetailScaffold } from '@/adapters/ui/shell/ToolDetailScaffold'
import { useOptionalBackend } from '@/adapters/backend/useOptionalBackend'
import { generateSshKey } from '@/adapters/backend/sshKeygenClient'
import {
  SSH_KEY_TYPE_LABELS,
  SshKeyGenerator,
  isClientSideKeyType,
  type SshKeyType,
} from '@/core/utility/sshKeyGenerator'

const generator = new SshKeyGenerator()
const ALL_KEY_TYPES = Object.keys(SSH_KEY_TYPE_LABELS) as SshKeyType[]

interface RenderedKey {
  keyTypeLabel: string
  publicKeyLine: string
  privateKeyPem: string
  fingerprint?: string
  encrypted: boolean
  viaBackend: boolean
}

export function SshKeygenScreen() {
  const [keyType, setKeyType] = useState<SshKeyType>('ed25519')
  const [comment, setComment] = useState('')
  const [passphrase, setPassphrase] = useState('')
  const [result, setResult] = useState<RenderedKey | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)

  const power = useOptionalBackend('ssh-keygen')
  const clientSide = isClientSideKeyType(keyType) && passphrase.length === 0
  const needsBackend = !clientSide

  const generate = useCallback(async () => {
    setError(null)
    setBusy(true)
    try {
      if (isClientSideKeyType(keyType) && passphrase.length === 0) {
        const v = generator.execute({ keyType, comment })
        setResult({
          keyTypeLabel: SSH_KEY_TYPE_LABELS[keyType],
          publicKeyLine: v.publicKeyLine,
          privateKeyPem: v.privateKeyPem,
          encrypted: false,
          viaBackend: false,
        })
        return
      }
      if (!power.available) {
        setResult(null)
        setError(
          `${SSH_KEY_TYPE_LABELS[keyType]}${passphrase ? ' (passphrase-protected)' : ''} keys are ` +
            'generated by the optional backend service, which is not connected. Start it and retry, ' +
            'or pick Ed25519 with no passphrase to generate here in the browser.',
        )
        return
      }
      const v = await generateSshKey(keyType, comment, passphrase)
      setResult({
        keyTypeLabel: SSH_KEY_TYPE_LABELS[keyType],
        publicKeyLine: v.publicKeyLine,
        privateKeyPem: v.privateKeyPem,
        fingerprint: v.fingerprintSha256,
        encrypted: v.encrypted,
        viaBackend: true,
      })
    } catch (e) {
      setResult(null)
      setError(e instanceof Error ? e.message : String(e))
    } finally {
      setBusy(false)
    }
  }, [keyType, comment, passphrase, power.available])

  // Generate an Ed25519 pair once on first mount so the screen is not empty.
  const didInit = useRef(false)
  useEffect(() => {
    if (didInit.current) return
    didInit.current = true
    void generate()
  }, [generate])

  return (
    <ToolDetailScaffold
      title="SSH Key Pair Generator"
      copyText={result?.publicKeyLine}
      inputPanel={
        <div className="flex max-w-sm flex-col gap-5">
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="ssh-keytype">Key type</Label>
            <Select value={keyType} onValueChange={(v) => setKeyType((v as SshKeyType | null) ?? 'ed25519')}>
              <SelectTrigger id="ssh-keytype" className="w-full" size="sm">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {ALL_KEY_TYPES.map((t) => (
                  <SelectItem key={t} value={t}>
                    {SSH_KEY_TYPE_LABELS[t]}
                    {isClientSideKeyType(t) ? '' : '  · backend'}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {needsBackend ? (
              <p className={`text-xs ${power.available ? 'text-muted-foreground' : 'text-amber-600 dark:text-amber-400'}`}>
                {power.available
                  ? 'Generated by the backend service (loopback only, key never written to disk).'
                  : 'Requires the backend service — not connected.'}
                {!power.available ? (
                  <Button variant="link" size="sm" className="h-auto px-1 py-0 text-xs" onClick={() => void power.retry()}>
                    retry
                  </Button>
                ) : null}
              </p>
            ) : null}
          </div>

          <div className="flex flex-col gap-1.5">
            <Label htmlFor="ssh-comment">Comment (optional)</Label>
            <Input
              id="ssh-comment"
              placeholder="e.g. you@yourhost"
              value={comment}
              onChange={(e) => setComment(e.target.value)}
            />
          </div>

          <div className="flex flex-col gap-1.5">
            <Label htmlFor="ssh-passphrase">Passphrase (optional — backend only)</Label>
            <Input
              id="ssh-passphrase"
              type="password"
              placeholder="encrypts the private key"
              value={passphrase}
              onChange={(e) => setPassphrase(e.target.value)}
            />
          </div>

          <Button type="button" className="w-fit gap-1.5" disabled={busy} onClick={() => void generate()}>
            {busy ? <Loader2 className="size-4 animate-spin" /> : <KeyRound className="size-4" />}
            {busy ? 'Generating…' : 'Regenerate'}
          </Button>
        </div>
      }
      outputPanel={
        <div className="flex flex-col gap-4">
          {error ? (
            <p className="text-sm text-destructive">{error}</p>
          ) : result ? (
            <>
              <Alert>
                <AlertTitle>Developer convenience tool</AlertTitle>
                <AlertDescription>
                  This is not a hardened HSM-grade key generator. The private key material is produced
                  {result.viaBackend ? ' by the local backend service' : ' in-process'} and shown in plain text
                  on screen. For anything you actually depend on — production servers, anything you cannot easily
                  rotate — generate the key with &quot;ssh-keygen&quot; on a trusted machine instead, or at
                  minimum regenerate this key if you have any doubt about how it was handled after being
                  displayed here.
                </AlertDescription>
              </Alert>
              <div className="flex flex-wrap gap-x-6 gap-y-1 text-xs text-muted-foreground">
                <span>
                  Type: <span className="font-mono text-foreground">{result.keyTypeLabel}</span>
                </span>
                {result.fingerprint ? (
                  <span>
                    Fingerprint: <span className="font-mono text-foreground">{result.fingerprint}</span>
                  </span>
                ) : null}
                {result.encrypted ? <span className="text-foreground">passphrase-encrypted</span> : null}
              </div>
              <CopyableBlock label="Public key (OpenSSH wire format)" text={result.publicKeyLine} />
              <CopyableBlock
                label={
                  result.encrypted
                    ? 'Private key (encrypted OpenSSH "openssh-key-v1" PEM)'
                    : 'Private key (unencrypted OpenSSH "openssh-key-v1" PEM)'
                }
                text={result.privateKeyPem}
              />
            </>
          ) : null}
        </div>
      }
    />
  )
}

function CopyableBlock({ label, text }: { label: string; text: string }) {
  const [copied, setCopied] = useState(false)

  async function handleCopy() {
    await navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 1000)
  }

  return (
    <div>
      <div className="mb-1.5 flex items-center justify-between">
        <p className="text-xs text-muted-foreground">{label}</p>
        <Button variant="ghost" size="sm" className="h-6 gap-1 px-1.5 text-xs" onClick={handleCopy}>
          <Copy className="size-3.5" />
          {copied ? 'Copied' : 'Copy'}
        </Button>
      </div>
      <pre className="max-w-full overflow-x-auto whitespace-pre-wrap break-all rounded-lg border border-border/60 bg-background p-3 font-mono text-xs">
        {text}
      </pre>
    </div>
  )
}
