import { describe, expect, it } from 'vitest'
import {
  ZabbixConfigBuilder,
  kZabbixServerParameterCatalog,
  kZabbixAgentParameterCatalog,
  zabbixCategoryOrderFor,
  zabbixConfigFileName,
  zabbixEffectiveOptions,
  zabbixIsLegalValue,
  zabbixParameterFor,
  zabbixSanitize,
} from './zabbixConfigBuilder'

describe('ZabbixConfigBuilder', () => {
  const builder = new ZabbixConfigBuilder()

  describe('server mode', () => {
    it('emits nothing but a hint when no directives are selected', () => {
      const output = builder.execute({ mode: 'server', selectedValues: {} })
      expect(output).toContain('No directives selected')
      expect(output).toContain('zabbix_server.conf')
    })

    it('only emits selected directives, grouped under category headers in a fixed order', () => {
      const output = builder.execute({
        mode: 'server',
        selectedValues: { DBName: 'zabbix', ListenPort: '10051', CacheSize: '16M', HousekeepingFrequency: '2' },
      })
      expect(output).toContain('# zabbix_server.conf — generated by InfraKit Studio')
      expect(output).toContain('### Database Connection')
      expect(output).toContain('DBName=zabbix')
      expect(output).toContain('### Network')
      expect(output).toContain('ListenPort=10051')
      expect(output.indexOf('### Database Connection')).toBeLessThan(output.indexOf('### Network'))
      expect(output).not.toContain('StartAgents')
    })

    it('does not accept an agent-only key', () => {
      const output = builder.execute({ mode: 'server', selectedValues: { StartAgents: '3' } })
      expect(output).toContain('No directives selected')
    })

    it('falls back to the catalog default for an out-of-range enumerated value', () => {
      const debugLevel = zabbixParameterFor('server', 'DebugLevel')!
      expect(zabbixIsLegalValue(debugLevel, '9')).toBe(false)
      const output = builder.execute({ mode: 'server', selectedValues: { DebugLevel: '9' } })
      expect(output).toContain(`DebugLevel=${debugLevel.defaultValue}`)
    })
  })

  describe('agent mode', () => {
    it('emits nothing but a hint referencing zabbix_agentd.conf when no directives are selected', () => {
      const output = builder.execute({ mode: 'agent', selectedValues: {} })
      expect(output).toContain('No directives selected')
      expect(output).toContain('zabbix_agentd.conf')
    })

    it('only emits selected agent directives, grouped under category headers in agent order', () => {
      const output = builder.execute({
        mode: 'agent',
        selectedValues: { Server: '10.0.0.5', Hostname: 'web01', StartAgents: '3', BufferSize: '200' },
      })
      expect(output).toContain('# zabbix_agentd.conf — generated by InfraKit Studio')
      expect(output).toContain('### Network')
      expect(output).toContain('Server=10.0.0.5')
      expect(output).toContain('### Host Identification')
      expect(output).toContain('Hostname=web01')
      expect(output).toContain('### Data Buffering')
      expect(output).toContain('BufferSize=200')
      expect(output.indexOf('### Network')).toBeLessThan(output.indexOf('### Host Identification'))
    })

    it('does not accept a server-only key', () => {
      const output = builder.execute({ mode: 'agent', selectedValues: { DBHost: 'localhost' } })
      expect(output).toContain('No directives selected')
    })

    it('DenyKey defaults to blocking system.run', () => {
      const denyKey = zabbixParameterFor('agent', 'DenyKey')!
      expect(denyKey.defaultValue).toBe('system.run[*]')
    })
  })

  it('the same key can mean different things in each catalog (ListenPort default differs)', () => {
    const serverListenPort = zabbixParameterFor('server', 'ListenPort')!
    const agentListenPort = zabbixParameterFor('agent', 'ListenPort')!
    expect(serverListenPort.defaultValue).toBe('10051')
    expect(agentListenPort.defaultValue).toBe('10050')
  })

  it('every catalog entry (both modes) has a resolvable category label and a non-empty description', () => {
    for (const parameter of [...kZabbixServerParameterCatalog, ...kZabbixAgentParameterCatalog]) {
      expect(parameter.description.length).toBeGreaterThan(0)
    }
    expect(zabbixCategoryOrderFor('server')).toContain('database')
    expect(zabbixCategoryOrderFor('agent')).toContain('activeChecks')
    expect(zabbixCategoryOrderFor('agent')).not.toContain('database')
  })

  it('boolean parameters expose the standard 0/1 option pair', () => {
    const allowRoot = zabbixParameterFor('agent', 'AllowRoot')!
    expect(zabbixEffectiveOptions(allowRoot).map((o) => o.value)).toEqual(['0', '1'])
  })

  it('zabbixSanitize is idempotent on an already-legal value', () => {
    const listenPort = zabbixParameterFor('server', 'ListenPort')!
    expect(zabbixSanitize(listenPort, '20051')).toBe('20051')
  })

  it('resolves the correct suggested filename per mode', () => {
    expect(zabbixConfigFileName('server')).toBe('zabbix_server.conf')
    expect(zabbixConfigFileName('agent')).toBe('zabbix_agentd.conf')
  })
})
