import 'dart:typed_data';
import 'dart:ui' show Size;

import 'package:flutter_test/flutter_test.dart';
import 'package:infrakit_studio/core/form_flow/pdf_form_generator.dart';
import 'package:infrakit_studio/core/form_flow/schema_model.dart';
import 'package:syncfusion_flutter_pdf/pdf.dart';

/// Re-opens generated bytes as a PDF. A corrupt document throws here, so a
/// successful load is itself the "is this a valid PDF" assertion — the same
/// proxy `test/core/office_media/pdf_split_merge_test.dart` uses.
PdfDocument _reopen(Uint8List bytes) => PdfDocument(inputBytes: bytes);

/// Every AcroForm field name in [document], in document order.
List<String> _fieldNames(PdfDocument document) =>
    [for (var i = 0; i < document.form.fields.count; i++) document.form.fields[i].name ?? ''];

SchemaField _text(String key, {String? value}) =>
    SchemaField(key: key, type: FieldType.text, defaultValue: value);

FormFlowSchema _schema(List<SchemaField> fields, {SourceFormat format = SourceFormat.xml, String root = 'config'}) =>
    FormFlowSchema(format: format, rootName: root, fields: fields);

void main() {
  const generator = PdfFormGenerator();

  group('PdfFormGenerator — document validity', () {
    test('produces bytes that re-open as a valid single-page PDF', () async {
      final bytes = await generator.generate(_schema([_text('host'), _text('port')]));

      expect(bytes.length, greaterThan(0));
      // %PDF- magic.
      expect(String.fromCharCodes(bytes.take(5)), '%PDF-');

      final document = _reopen(bytes);
      expect(document.pages.count, 1);
      document.dispose();
    });

    test('an empty schema still produces a valid one-page PDF with no fields', () async {
      final bytes = await generator.generate(_schema(const []));

      final document = _reopen(bytes);
      expect(document.pages.count, 1);
      expect(document.form.fields.count, 0);
      document.dispose();
    });
  });

  group('PdfFormGenerator — field mapping', () {
    test('text and number become text boxes, boolean becomes a check box', () async {
      final bytes = await generator.generate(
        _schema([
          _text('host'),
          const SchemaField(key: 'port', type: FieldType.number, defaultValue: '8080'),
          const SchemaField(key: 'tls', type: FieldType.boolean, defaultValue: 'true'),
        ]),
      );

      final document = _reopen(bytes);
      expect(document.form.fields.count, 3);
      expect(_fieldNames(document), ['host', 'port', 'tls']);
      expect(document.form.fields[0], isA<PdfTextBoxField>());
      expect(document.form.fields[1], isA<PdfTextBoxField>());
      expect(document.form.fields[2], isA<PdfCheckBoxField>());
      document.dispose();
    });

    test('pre-fills text/number values and the boolean checked state', () async {
      final bytes = await generator.generate(
        _schema([
          _text('host'),
          const SchemaField(key: 'port', type: FieldType.number),
          const SchemaField(key: 'tls', type: FieldType.boolean),
        ]),
        values: {'host': 'db-01.internal', 'port': 5432, 'tls': true},
      );

      final document = _reopen(bytes);
      expect((document.form.fields[0] as PdfTextBoxField).text, 'db-01.internal');
      expect((document.form.fields[1] as PdfTextBoxField).text, '5432');
      expect((document.form.fields[2] as PdfCheckBoxField).isChecked, isTrue);
      document.dispose();
    });

    test('falls back to the schema default when a value is absent', () async {
      final bytes = await generator.generate(_schema([_text('host', value: 'localhost')]));

      final document = _reopen(bytes);
      expect((document.form.fields[0] as PdfTextBoxField).text, 'localhost');
      document.dispose();
    });

    test('object children get dotted, path-qualified names', () async {
      final bytes = await generator.generate(
        _schema([
          const SchemaField(
            key: 'database',
            type: FieldType.object,
            children: [
              SchemaField(key: 'host', type: FieldType.text),
              SchemaField(key: 'port', type: FieldType.number),
            ],
          ),
        ]),
      );

      final document = _reopen(bytes);
      expect(_fieldNames(document), ['database.host', 'database.port']);
      document.dispose();
    });

    test('a dot inside a schema key is escaped so it cannot forge a path segment', () async {
      final bytes = await generator.generate(_schema([_text('a.b')]));

      final document = _reopen(bytes);
      expect(_fieldNames(document), ['a_b']);
      document.dispose();
    });
  });

  group('PdfFormGenerator — arrays', () {
    const arraySchemaField = SchemaField(
      key: 'server',
      type: FieldType.array,
      children: [
        SchemaField(key: 'host', type: FieldType.text),
        SchemaField(key: 'port', type: FieldType.number),
      ],
    );

    test('with no values, repeats the item template blankArrayRepetitions times', () async {
      final bytes = await generator.generate(_schema([arraySchemaField]));

      final document = _reopen(bytes);
      // 3 blank repetitions x 2 fields.
      expect(document.form.fields.count, 6);
      expect(_fieldNames(document), [
        'server.1.host', 'server.1.port',
        'server.2.host', 'server.2.port',
        'server.3.host', 'server.3.port',
      ]);
      document.dispose();
    });

    test('honours a custom blankArrayRepetitions', () async {
      const wide = PdfFormGenerator(blankArrayRepetitions: 5);
      final bytes = await wide.generate(_schema([arraySchemaField]));

      final document = _reopen(bytes);
      expect(document.form.fields.count, 10);
      document.dispose();
    });

    test('with values, emits exactly one block per item and pre-fills each', () async {
      final bytes = await generator.generate(
        _schema([arraySchemaField]),
        values: {
          'server': [
            {'host': 'a', 'port': 1},
            {'host': 'b', 'port': 2},
          ],
        },
      );

      final document = _reopen(bytes);
      expect(_fieldNames(document), ['server.1.host', 'server.1.port', 'server.2.host', 'server.2.port']);
      expect((document.form.fields[0] as PdfTextBoxField).text, 'a');
      expect((document.form.fields[2] as PdfTextBoxField).text, 'b');
      document.dispose();
    });

    test('repeated blocks never collide on a name (no GUID renaming by fieldAutoNaming)', () async {
      final bytes = await generator.generate(_schema([arraySchemaField]));

      final document = _reopen(bytes);
      final names = _fieldNames(document);
      expect(names.toSet().length, names.length, reason: 'field names must be unique');
      expect(names.every((n) => n.startsWith('server.')), isTrue,
          reason: 'a collision would leave a random-GUID name behind');
      document.dispose();
    });

    test('nested arrays flatten into indexed names at both levels', () async {
      final bytes = await generator.generate(
        _schema([
          const SchemaField(
            key: 'server',
            type: FieldType.array,
            children: [
              SchemaField(key: 'host', type: FieldType.text),
              SchemaField(
                key: 'disk',
                type: FieldType.array,
                children: [SchemaField(key: 'mount', type: FieldType.text)],
              ),
            ],
          ),
        ]),
        values: {
          'server': [
            {
              'host': 'a',
              'disk': [
                {'mount': '/'},
                {'mount': '/data'},
              ],
            },
          ],
        },
      );

      final document = _reopen(bytes);
      expect(_fieldNames(document), ['server.1.host', 'server.1.disk.1.mount', 'server.1.disk.2.mount']);
      expect((document.form.fields[2] as PdfTextBoxField).text, '/data');
      document.dispose();
    });

    test('an array with no item template emits a heading and no fields', () async {
      final bytes = await generator.generate(
        _schema([const SchemaField(key: 'tags', type: FieldType.array)]),
      );

      final document = _reopen(bytes);
      expect(document.form.fields.count, 0);
      expect(document.pages.count, 1);
      document.dispose();
    });
  });

  group('PdfFormGenerator — pagination', () {
    test('a schema too tall for one page flows onto further pages', () async {
      final fields = [for (var i = 0; i < 60; i++) _text('field_$i')];

      final bytes = await generator.generate(_schema(fields));

      final document = _reopen(bytes);
      expect(document.pages.count, greaterThan(1),
          reason: '60 rows cannot fit in one A4 client area');
      expect(document.form.fields.count, 60, reason: 'no field may be dropped by a page break');
      expect(_fieldNames(document), [for (var i = 0; i < 60; i++) 'field_$i']);
      document.dispose();
    });

    test('every field stays inside its page, never running off the bottom', () async {
      final fields = [for (var i = 0; i < 90; i++) _text('field_$i')];

      final bytes = await generator.generate(_schema(fields));

      final document = _reopen(bytes);
      expect(document.pages.count, greaterThanOrEqualTo(3));
      for (var p = 0; p < document.pages.count; p++) {
        final page = document.pages[p];
        for (var a = 0; a < page.annotations.count; a++) {
          final bounds = page.annotations[a].bounds;
          expect(bounds.top, greaterThanOrEqualTo(0));
          expect(bounds.bottom, lessThanOrEqualTo(page.size.height),
              reason: 'a widget on page ${p + 1} spills past the page edge');
        }
      }
      document.dispose();
    });

    test('a large array paginates and keeps every repetition addressable', () async {
      const many = PdfFormGenerator(blankArrayRepetitions: 40);
      final bytes = await many.generate(
        _schema([
          const SchemaField(
            key: 'server',
            type: FieldType.array,
            children: [
              SchemaField(key: 'host', type: FieldType.text),
              SchemaField(key: 'enabled', type: FieldType.boolean),
            ],
          ),
        ]),
      );

      final document = _reopen(bytes);
      expect(document.pages.count, greaterThan(1));
      expect(document.form.fields.count, 80);
      final names = _fieldNames(document);
      expect(names.toSet().length, 80);
      expect(names.contains('server.40.enabled'), isTrue);
      document.dispose();
    });

    test('a smaller page size paginates sooner', () async {
      final fields = [for (var i = 0; i < 20; i++) _text('field_$i')];
      const small = PdfFormGenerator(pageSize: Size(300, 300), margin: 20);

      final bytes = await small.generate(_schema(fields));

      final document = _reopen(bytes);
      expect(document.pages.count, greaterThan(1));
      expect(document.form.fields.count, 20);
      expect(document.pages[0].size.width, closeTo(300, 0.5));
      document.dispose();
    });
  });

  group('PdfFormGenerator — robustness', () {
    test('a values tree whose shape contradicts the schema renders blank, not an exception', () async {
      final bytes = await generator.generate(
        _schema([
          _text('host'),
          const SchemaField(
            key: 'db',
            type: FieldType.object,
            children: [SchemaField(key: 'name', type: FieldType.text)],
          ),
        ]),
        // host is given a Map, db is given a scalar — both wrong.
        values: {
          'host': {'oops': 1},
          'db': 'not-an-object',
        },
      );

      final document = _reopen(bytes);
      expect(_fieldNames(document), ['host', 'db.name']);
      expect((document.form.fields[0] as PdfTextBoxField).text, '');
      document.dispose();
    });

    test('an explicit title overrides the schema-derived one', () async {
      final bytes = await generator.generate(_schema([_text('host')]), title: 'Deployment Request');

      final document = _reopen(bytes);
      expect(PdfTextExtractor(document).extractText(startPageIndex: 0), contains('Deployment Request'));
      document.dispose();
    });

    test('draws the field label as page text next to the widget', () async {
      final bytes = await generator.generate(_schema([_text('hostname')]));

      final document = _reopen(bytes);
      final text = PdfTextExtractor(document).extractText(startPageIndex: 0);
      expect(text, contains('hostname'));
      document.dispose();
    });
  });
}
